locations = [{'name': 'Idaho Falls',
              'state' :'ID',
              'abbreviation': ['INL', 'inl'],
              'lon': -112.928561,
              'lat': 43.594919,
              'alt' :1496.5,
              'timezone': -7,
              'type': 'permanent'
              },
              {'name': 'Bondville',
              'state' :'IL',
              'abbreviation': ['BND', 'bon'],
              'lon': -88.37309,
              'lat': 40.05192,
              'alt' :230,
              'timezone': -6,
              'type': 'permanent'},
             {'name': 'Sioux Falls',
              'state': 'SD',
              'abbreviation': ['SXF', 'sxf'],
              'lon': -96.62328,
              'lat': 43.73403,
              'alt': 473,
              'timezone': -6,
              'type': 'permanent'},
             {'name': 'Table Mountain',
              'state': 'CO',
              'abbreviation': ['TBL', 'tbl'],
              'lon': -105.23680,
              'lat': 40.12498,
              'alt': 1689,
              'timezone': -7,
              'type': 'permanent'},
             {'name': 'Desert Rock',
              'state': 'NV',
              'abbreviation': ['DRA', 'dra'],
              'lon': -116.01947,
              'lat': 36.62373,
              'alt': 1007,
              'timezone': 8,
              'type': 'permanent'},
             {'name': 'Fort Peck',
              'state': 'MT',
              'abbreviation': ['FPK', 'fpk'],
              'lon': -105.10170,
              'lat': 48.30783,
              'alt': 634,
              'timezone': 7,
              'type': 'permanent'},
             {'name': 'Goodwin Creek',
              'state': 'MS',
              'abbreviation': ['GWN', 'gwn'],
              'lon': -89.8729,
              'lat': 34.2547,
              'alt': 98,
              'timezone': 6,
              'type': 'permanent'},
             {'name': 'Penn. State Univ.',
              'state': 'PA',
              'abbreviation': ['PSU', 'psu'],
              'lon': -77.93085,
              'lat': 40.72012,
              'alt': 376,
              'timezone': 5,
              'type': 'permanent'},
             {'name': 'ARM Southern Great Plains Facility',
              'state': 'OK',
              'abbreviation': ['SGP', 'sgp'],
              'lon': -97.48525,
              'lat': 36.60406,
              'alt': 314,
              'timezone': 6,
              'type': 'permanent'},
             # {'name': '',
             #  'state': '',
             #  'abbreviation': ['', ''],
             #  'lon': -,
             #  'lat': ,
             #  'alt': ,
             #  'timezone': ,
             #  'type': 'permanent'}
             ]