locations = [{'name': 'Bondville', 'state':'IL', 'abbriviations': ['bon'], 'lon:': 0, 'lat:': 0}]

locations = [{'name': 'Bondville',
              'state' :'IL',
              'abbriviations': ['BND', 'bon'],
              'lon': -88.37309,
              'lat': 40.05192,
              'alt' :230,
              'timezone': -6},
             {'name': 'Sioux Falls',
              'state': 'SD',
              'abbriviations': ['SXF', 'sxf'],
              'lon': -96.62328,
              'lat': 43.73403,
              'alt': 473,
              'timezone': -6},
             {'name': 'Table Mountain',
              'state': 'CO',
              'abbriviations': ['TBL', 'tbl'],
              'lon': -105.23680,
              'lat': 40.12498,
              'alt': 1689,
              'timezone': -7},
             {'name': 'Desert Rock',
              'state': 'NV',
              'abbriviations': ['DRA', 'dra'],
              'lon': -116.01947,
              'lat': 36.62373,
              'alt': 1007,
              'timezone': 8},
             {'name': 'Fort Peck',
              'state': 'MT',
              'abbriviations': ['FPK', 'fpk'],
              'lon': -105.10170,
              'lat': 48.30783,
              'alt': 634,
              'timezone': 7},
             {'name': 'Goodwin Creek',
              'state': 'MS',
              'abbriviations': ['GWN', 'gwn'],
              'lon': -89.8729,
              'lat': 34.2547,
              'alt': 98,
              'timezone': 6},
             {'name': 'Penn. State Univ.',
              'state': 'PA',
              'abbriviations': ['PSU', 'psu'],
              'lon': -77.93085,
              'lat': 40.72012,
              'alt': 376,
              'timezone': 5},
             {'name': 'ARM Southern Great Plains Facility',
              'state': 'OK',
              'abbriviations': ['SGP', 'sgp'],
              'lon': -97.48525,
              'lat': 36.60406,
              'alt': 314,
              'timezone': 6},
             # {'name': '',
             #  'state': '',
             #  'abbriviations': ['', ''],
             #  'lon': -,
             #  'lat': ,
             #  'alt': ,
             #  'timezone': }
             ]