#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  6 09:44:01 2023

@author: hagen
This script is performing the inversion based on Johns retrieval (AOD1)
"""

import SurfRadPy.aodinversion as sfraodinv

if __name__ == '__main__':
    sfraodinv.produce_aodinversion1_01()
    