#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  6 09:44:01 2023

@author: hagen
"""

import productomator.lab as prolab
import SurfRadPy.aodinversion as sfraodinv

if __name__ == '__main__':

    