#!/usr/bin/perl
#
# The input .tu file should be generated by:
#  tu -d joe -r start -z <tz> -x maez -c <solfile> -H -o <output_file> file.mtm
#
# To run:  perl tu2ccc.pl <site> <start_date> <end_date>
#
use strict;
use lib "/home/grad/mfrsr/bin";
use Modules::Check_Site;
use Modules::Check_Dates;
use Modules::Determine_Dates;
use Modules::Site_Info;
use Time::Local;  # Necessary when using SUNAE

# Make sure it is user mfrsr running the program
my $user = getlogin();
if ($user !~ /^mfrsr/) {
    print "\n Derp! You are running as user: $user\n";
    print " This program needs to be run by user \'mfrsr\' in order";
    print " to create\n the directories and files with proper ownership.\n";
    die "\n";
}

if (scalar@ARGV != 3) {usage();}
my $tli   = $ARGV[0];
my $start = $ARGV[1];
my $end   = $ARGV[2];
my $type  = "mfrsr"; # This will need to be changed to a command line
                     # variable if tu2ccc.pl is ever used for MFRs.

my $tli_type = join('_',$tli,$type);  # Because Check_Site needs TLI_TYPE
my @tlidir = &Check_Site ($tli_type); # Make sure site is valid
&Check_Dates ($start,$end);           # Make sure dates are valid

my @dates = &Determine_Dates ($start,$end); # Returns array of dates (yyyymmdd)

# Gather site attributes from site_info file
#
# "new_date" is the date the new style head went into operation
#
my %info = &Site_Info ($tli_type); # Returns lat, lon, tz, new_date

my $lat  = $info{LAT};
my $lon  = $info{LON};
my $tz   = $info{TZ};
my $dir  = $info{DIR};

# Copy raw files for date range requested into temp directory
#
my $tmp = "/tmp/mfrsrcccproc";
`rm -rf $tmp`;
`mkdir $tmp`;
my $path = "/data/Inst/MFR/${dir}/${tli}/${type}";  # Common path
foreach (@dates) {
    my $yyyy = substr($_,0,4);
    `cp ${path}/tu/${yyyy}/${tli}_${type}_${_}\*\.tu $tmp`;
}

chdir "$tmp";
my @files = `ls \*\.tu`;
if (scalar @files == 0) {die "\nNo .tu files to process";}

foreach my $file (@files) {
    chomp $file;
    print STDOUT "Processing: $file\n";
    my ($hexb,$hexh,$sn) = (split /_/,$file)[3,4,5];
    $sn = (split '\.',$sn)[0];
    $sn = sprintf "%4.4d",$sn;

    my $year    = substr($file,10,4);
    my $month   = substr($file,14,2);
    my $day     = substr($file,16,2);

    open (IF, "<$file");
    open (OF, ">${tli}${year}${month}${day}_${sn}.ccc");

    my @header = (split /\s+/, `head -1 $file`); # For formatting write
    my $rev    = $header[0]; # Software Revision
    my $init;
    if ($rev != 11) {
	$init = $header[12]; # For formatting write
    } else {
	$init = -9;
    }

    my ($srt,$dlv);
    my $next_flag = "Y";
    while (<IF>) {
	chomp;
	if ($next_flag eq "Y") {
	    my $idh = (split/\s+/, $_)[2];
	    if (length($idh) == 3) {$idh = sprintf "%1d%3s", "0",$idh;}
	    if ($idh eq "0") {$idh = sprintf "%4.4d", $idh;}
	    if ($hexh ne $idh) {
		print "\nID from filename:                $hexh\n";
                print "does not match string from file: $idh\n\n";
	    }
	    $next_flag = "N"; 
	    next;
	}
	my @el    = split/\s+/, $_;
	my $size  = @el;

###########################################
# 19700101 - 19000101 = 2208988800 seconds
#
# Using the above constant to simplify time/date calculations.  That
# number is the elapsed seconds between 1 Jan 1900 and 1 Jan 1970.
#
# tu (raw2tu.pl) is configured to output time in LST to be compatible
# with the Langley analysis (la) program.  So below we are accounting
# for that and first converting to GMT by using $tz from site attributes.
#
        $el[0] = $el[0] - $tz/24;  # Converting to GMT
	my $secs = int($el[0] * 86400 + 0.5)-86400-2208988800;
	my ($ss,$mn,$hh,$dd,$mm,$yyyy) = (gmtime($secs))[0,1,2,3,4,5];
	$yyyy += 1900;
	$mm++;

##########################################
# Uncomment next five lines to use included SUNAE code rather than 
# values from tu.  (Note that tu also uses SUNAE).  Will then
# need to comment the following two lines.
#
        my $cdiy = ((gmtime(timegm(0,0,0,$dd,$mm-1,$yyyy)))[7])+1; #Current DIY
        my $fhr = $hh + ($mn*60 + $ss)/3600;  # Fractional Hour
        my @sunae = sunae($yyyy,$cdiy,$fhr,$lat,$lon);
        my $az    = $sunae[0];
        my $sza   = 90-$sunae[1];
#	my $az    = $el[$size-3];   # Comment if using preceding SUNAE calcs
#	my $sza   = $el[$size-1];   # Comment if using preceding SUNAE calcs
	my $csza  = cos(deg2rad($sza));

##########################################
# Head temperature calculation.  Code taken from Yankee MFRSR cal file.
#
# $init=0 means no srt or dlv

	if (($init > 0) && ($el[1] > 2000)) {
	    $srt = 6810 * (5000 / $el[1] -1);
	    $srt = 1.030852e-3+2.389179e-4 * 
		log($srt) + 1.574641e-7 * log($srt)**3;
	    $srt = 1.0 / $srt - 273.12;
	} else {
	    $srt = -99.9;
	}
	
##########################################
# Data logger supply voltage.  Code taken from Yankee MFRSR cal file.
#
# $init=0 means no srt or dlv
#
	if (($init eq "11FF") || ($init eq "1FF") || ($init == 1)) { 
	    $dlv = $el[9] * 6.0 / 1000.0;
	} elsif ($init == 101) {
	    $dlv = $el[2] * 6.0 / 1000.0;
	} elsif ($init <= 0) {
	    $dlv = -99.9;
	} else {
	    print "\n            *** ERROR! ***\n";
	    print " Check init string in header of $file\n";
	    print " The init string found is: $init\n";
	    print " Expected strings are 11FF, 1FF, or 1\n";
	    print " Was it created with proper flags in raw2tu.pl?\n";
	    print " e.g., tu -d joe -x maez -H raw.xmd\n";
	    print " If so, raw file likely has unique initialization\n\n";
	    die;
	}

##########################################
# Begin print statement for outputting ccc data files
#
#
	if (($ss == 0) && ($sza < 95)) {
	    if ($init eq "11FF") { # Need to shift @el index by 1 if true
		printf OF "%11.5f %7.5f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %5.2f %5.2f\n",$el[0],$csza,@el[11..31],$srt,$dlv;
	    } elsif ($init eq "1FF") {
		printf OF "%11.5f %7.5f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %5.2f %5.2f\n",$el[0],$csza,@el[10..30],$srt,$dlv;
	    } elsif ($init eq "101") {
		printf OF "%11.5f %7.5f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %5.2f %5.2f\n",$el[0],$csza,@el[3..23],$srt,$dlv;
	    } elsif ($init eq "1") {
		printf OF "%11.5f %7.5f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %5.2f %5.2f\n",$el[0],$csza,@el[3..23],$srt,$dlv;
	    } elsif ($init <= 0) {
		printf OF "%11.5f %7.5f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %7.2f %5.2f %5.2f\n",$el[0],$csza,@el[1..21],$srt,$dlv;
	    } else {
		print "\n            *** ERROR! ***\n";
		print " Check init string in header of $file\n";
		print " The init string found is: $init\n";
		print " Expected strings are 11FF, 1FF, 101, 1, 0\n";
		print " Was it created with proper flags in raw2tu.pl?\n";
		print " e.g., tu -d joe -x maez -H raw.xmd\n";
		print " If so, raw file likely has unique initialization\n\n";
		die;
	    }
	}
    }
    close (OF);
    close (IF);
}

##########################################
# Check if .ccc file size is zero.  Delete if it is.
# Move non-zero .ccc files to regular directory structure
#
print "\n";
my @cccfiles = `ls \*\.ccc`;
if (scalar @cccfiles == 0) {die "\nNo .ccc files to process";}
foreach my $ccc (@cccfiles) {
    chomp $ccc;
    if (-z $ccc) {
	print "$ccc is zero size and is being deleted\n";
	`rm -rf $ccc`;
    }
}

print "\nMoving .ccc files to ${path}/ccc/<YYYY>\n\n";
my @cccfiles = `ls \*\.ccc`; # Some may have been removed due to zero size
foreach my $ccc (@cccfiles) {
    chomp $ccc;
    my $yyyy = substr($ccc,3,4);
    if (! -e "${path}/ccc/${yyyy}/") {   # Dir exist?
	`mkdir -p ${path}/ccc/${yyyy}/`; # Create
    }
    `mv ${tmp}/${ccc} ${path}/ccc/${yyyy}/`;
}
    
##########################################
# Clean up
#
`rm -rf $tmp`;


# Subroutines below
#
# ===================================


sub usage {
    use strict;
    print "\n  To run, type \"perl tu2ccc.pl <site> <begin_date> <end_date>\"\n\n";
    print "  Site should be one of: bnd dra fpe gwn psu sxf tbl twr lab\n";
    print "  Dates should be in YYYYMMDD format\n\n";
    die;
}
1;



###############################################################################
# Subroutine sunae
#
# Calculates the Azimuth, Elevation, Solar Distance and Disk Diameter
#
# Fixed some errors in the refraction code on 20111108
#
###############################################################################
sub sunae () {
    use Math::Trig;
#    use strict;
    my $year = shift(@_);
    my $day  = shift(@_);
    my $hour = shift(@_); # Fractional hour
    my $lat  = shift(@_);
    my $long = shift(@_);

    my ($refrac);

    if ($year < 1950 || $year > 2050) {
        die "SUNAE--bad input variable YEAR ($year), stopped\n";
    }
    if ($day < 1 || $day > 366) {
        die "SUNAE--bad input variable DAY ($day), stopped\n";
    }
    if ($hour < -13.0 || $hour > 36.0) {
        die "SUNAE--bad input variable HOUR ($hour), stopped\n";
    }
    if ($lat < -90 || $lat > 90) {
        die "SUNAE--bad input variable LAT ($lat), stopped\n";
    }
    if ($long < -180 || $long > 180) {
        die "SUNAE--bad input variable LON ($long), stopped\n";
    }

    my $pi    = atan2(1,1) * 4;
    my $twopi = 2.0 * $pi;
    my $rpd   = $pi/180;

#                    ** current Julian date (actually add 2,400,000
#                    ** for true JD);  LEAP = leap days since 1949;
#                    ** 32916.5 is midnite 0 jan 1949 minus 2.4e6

    my $delta = $year - 1949;
    my $leap  = int($delta / 4);
    my $jd = 32916.5 + ($delta*365 + $leap + $day) + ($hour/24.);
#
#                    ** last yr of century not leap yr unless divisible
#                    ** by 400 (not executed for the allowed YEAR range,
#                    ** but left in so our successors can adapt this for
#                    ** the following 100 years)


    if (($year % 100 == 0) && ($year % 400 != 0)) {
        $jd = $jd - 1;
    }

#                     ** ecliptic coordinates
#                     ** 51545.0 + 2.4e6 = noon 1 jan 2000

    my $time = $jd - 51545.0;

#                    ** force mean longitude between 0 and 360 degs

    my $mnlong = 280.460 + (0.9856474 * $time);
#    $mnlong = ($mnlong % 360);
    while ($mnlong > 360) { $mnlong = $mnlong - 360; }

#                    ** mean anomaly in radians between 0 and 2*pi

    my $mnanom = 357.528 + (0.9856003 * $time);
#    $mnanom = ($mnanom % 360);
    if ($mnanom < 0) { $mnanom = $mnanom + 360; }
    $mnanom = $mnanom * $rpd;

#                    ** ecliptic longitude and obliquity
#                    ** of ecliptic in radians

    my $eclong = $mnlong + 1.915*sin($mnanom) + 0.020*sin(2*$mnanom);
    while ($eclong > 360) { $eclong = $eclong - 360; }

    my $oblqec = 23.439 - 0.0000004*$time;
    $eclong = $eclong*$rpd;
    $oblqec = $oblqec*$rpd;

#                    ** right ascension

    my $num  = cos($oblqec)*sin($eclong);
    my $den  = cos($eclong);
    my $temp = $num/$den;
    my $ra   = atan($num/$den);

#                    ** Force right ascension between 0 and 2*pi

    if ($den < 0) {
        $ra  = $ra + $pi;
    } elsif ($num < 0) {
        $ra  = $ra + $twopi;
    }

#                    ** declination

    my $dec = asin(sin($oblqec)*sin($eclong));

#                    ** Greenwich mean sidereal time in hours

    my $gmst = 6.697375 + 0.0657098242*$time + $hour;

#                    ** Hour not changed to sidereal time since
#                    ** 'time' includes the fractional day

    while ($gmst > 24) { $gmst = $gmst - 24; }

#                    ** local mean sidereal time in radians

    my $lmst  = $gmst + $long/15;
    while ($lmst > 24) { $lmst = $lmst - 24; }
    $lmst   = $lmst * 15 * $rpd;

#                    ** hour angle in radians between -pi and pi

    my $ha  = $lmst - $ra;
    if ($ha < -$pi) { $ha  = $ha + $twopi; }
    if ($ha > $pi) { $ha  = $ha - $twopi; }

#                    ** solar azimuth and elevation

    my $el = asin(sin($dec) * sin($lat * $rpd) +
               cos($dec) * cos($lat * $rpd) * cos($ha));

    my $az = asin(-cos($dec) * sin($ha) / cos($el));

#                    ** Put azimuth between 0 and 2*pi radians

    if ((sin($dec) - sin($el) * sin($lat * $rpd)) > 0) {
        if (sin($az) < 0) { $az = $az + $twopi; }
    } else {
        $az = $pi - $az;

    }

#                     ** Convert elevation and azimuth to degrees
    $az  =  $az / $rpd;
    $el  =  $el / $rpd;

#  ======== Refraction correction for U.S. Standard Atmos. ==========
#      (assumes elevation in degs) (3.51823=1013.25 mb/288 K)

    if ($el > 19.225 ) {
        $refrac = 0.00452*3.51823 / tan($el*$rpd);
    } elsif ($el > -0.766 && $el < 19.225 ) {
        $refrac = 3.51823 * (0.1594 + 0.0196*$el + 0.00002*$el**2) /
            (1 + 0.505*$el + 0.0845*$el**2);

    } elsif ($el <= -0.766 ) {
        $refrac = 0.0;
    }
    $el = $el + $refrac;

# ===================================================================

#                   ** distance to sun in A.U. & diameter in degs

    my $soldst = 1.00014 - 0.01671*cos($mnanom) - 0.00014*cos(2*$mnanom);
    my $soldia = 0.5332 / $soldst;

    if ($el < -90 || $el > 90) {
        die "SUNAE--Output argument EL ($el) out of range\n";
    }
    if ($az < 0 || $az > 360) {
        die "SUNAE--Output argument AZ out of range\n";
    }
    my @returnary = ($az, $el, $soldst, $soldia);
    return (@returnary);
}
1;
