
#!/usr/bin/perl
#
# The input .tu file should be generated by:
#  tu -d joe -r start -z <tz> -x maez -c <solfile> -H -o <output_file> file.mtm
#
# To run:  perl tu2cal.pl <site> <type> <start_date> <end_date>
#
use strict;
use Time::Local;

# Home-brewed and other modules that are common to multiple programs.
use lib "/home/grad/mfrsr/bin";
use Modules::Check_Site;
use Modules::Check_Dates;
use Modules::Determine_Dates;
use Modules::Site_Info;
use Modules::Time_Calculations;
use Modules::SUNAE;

# Make sure it is user mfrsr running the program
my $user = getlogin();
if ($user !~ /^mfrsr/) {
    print "\n Derp! You are running as user: $user\n";
    print " This program needs to be run by user \'mfrsr\' in order";
    print " to create\n the directories and files with proper ownership.\n";
    die "\n";
}

if (scalar@ARGV != 4) {usage();}
my $tli   = $ARGV[0];
my $type  = $ARGV[1];
my $start = $ARGV[2];
my $end   = $ARGV[3];

my $tli_type = join('_',$tli,$type);
&Check_Site($tli_type);    # Make sure site is valid
&Check_Dates($start,$end); # Make sure dates are valid
my @dates = &Determine_Dates($start,$end);


############################################################################
# Gather site attributes from site_info file.  Necessary to determine site
# type (mfrsr or tower), and for lat/lon if using SUNAE code
#
my %info   = &Site_Info($tli_type); # Ret lat, lon, tz, new_date
my $lat    = $info{LAT};
my $lon    = $info{LON};
my $tz     = $info{TZ};
my $tpdate = $info{NEW};
my $dir    = $info{DIR};

# Establish variable for temporary directory
my $tdir = "/tmp/mfrsrcalproc";
`rm -rf $tdir`;
`mkdir $tdir`;

############################################################################
# Copy .tu files for date range requested into temp directory, and then 
# cd to that directory.  Includes check for existence of files to process.
#
print "\n  Copying files to $tdir\n\n";
my $path = "/data/Inst/MFR/${dir}/${tli}/${type}";  # Common Path
foreach my $date (@dates) {
    my $yyyy = substr($date,0,4);
    `cp ${path}/tu/${yyyy}/${tli}_${type}_${date}*\.tu $tdir`;
}
chdir "$tdir";  # Changing to temporary directory $tdir
my @files = `ls \*\.tu`;
if (scalar @files == 0) {die "\nNo .tu files to process";}

############################################################################
# Begin loop to process each file.
#
foreach my $file (@files) {

# Pulling info from tu filename
    chomp $file;
    print STDOUT "Processing tu file: $file\n";
    my ($date,$hexb,$hexh,$sn) = (split /_/,$file)[2,3,4,5];
    $sn = sprintf "%4.4d",$sn;

############################################################################
# Retrieve calibration information from file located in
# /home/grad/mfrsr/Calinfo/CAL
#
# Returns refs to hashes for Cals and Offsets, and
# a hash ref of sensor info (serial number, head hexID, log hexID)
#
# $rCAL & $cOS keys are: ch1, ch2...ch7, where ch1=BB, ch4=615|1625
#
    my ($rCAL,$rOS,$rINFO) = calibration($tli,$type,$date,$file); 

#    print "working\n";
#    foreach my $k1 (keys %$rCAL) {
#	print "> $k1 @{$$rCAL{$k1}}\n";
#    }
#    print "working\n";
#    sleep 2;
############################################################################
# Gather logger gain/offset information for apropriate logger from 
# /home/grad/mfrsr/Calinfo/LoggerGains
#
# keys are: ch1, ch2 ... ch7, where ch1=BB, ch4=615|1625
#
    my $rGAIN = loggergains($hexb); # Hash ref to Logger Gains and Offsets

############################################################################
# Gather diffuse correction information.  Returns a hash reference ($rDC) 
# of the corrections.
#
# keys are: ch1, ch2 ... ch7, where ch1=BB, ch4=615|1625
#
    my $rDC = diffusecorr($tli,$type,$date,$lat,$file);


    my $header_flag = "N"; # To read header line
    my $tpf = "N";         # Thermopile instrument (Y/N)
    my $z;                 # Array (@el) index adjustment for TP/si, etc.
    my $addflds = "N";     # Additional fields (UVB_Sig, UVB_Temp, and PAR)
    my $ctype;             # Var that holds the calibration type, e.g., Yankee
    my $rLAMP;             # Hash Ref to Standard Lamp data
    open (IF, "<$file");
    open (OF, ">${tli}_${type}_${date}_${sn}.cal");
    while (<IF>) {
	chomp;
	my ($srt,$dlv); # Head_Temp, Log_V
#
# Several things are done with the header line of each file
#	
	if ($header_flag eq "N") {
	    $header_flag = "Y"; 
	    if ($hexh =~ /\d\d\d\d/) {$hexh = int($hexh);} # Set to 0 if 0000
	    my ($idb,$idh,$init) = (split/\s+/, $_)[1,2,12];
	    $idh = sprintf "%04s",$idh;  # Pad with zeros
	    $idb = sprintf "%04s",$idb;  # Pad with zeros
	    if ($hexh ne $idh) {
		print "\nHead ID from filename:           \"$hexh\"\n";
                print "does not match string from file: \"$idh\"\n\n";
	    }
	    if ($hexb ne $idb) {
		print "\nBoard ID from filename:          \"$hexb\"\n";
                print "does not match string from file: \"$idb\"\n\n";
	    }

###############################################################################
# Determine indexing adjustment for data based on the initialization string
# and the flags set in the poll.pl config files.  Necessary to correctly
# apply cals as @el size varies depending on instrument config.  We also set
# the flag in this section to indicate a thermopile instrument.  This
# cannot be done solely by interrogating the raw/tu files, so we have to
# also rely on the date a thermopile unit was installed.
#
#  flag = 20, MFRSR
#  11FF = Array size 36, Alltime channels w/head_temp, log_volt, and therm_volt
#   1FF = Array size 35, Alltime channels w/head_temp and log_volt
#   101 = Array size 28, Alltime channels off, head_temp and log_volt
#
#  flag = 00, MFR10
#  11FF = Array size 15, Alltime channels w/head_temp, log_volt, and therm_volt
#  73FF = Array size xx, Alltime channels as above with UVB_Sig, UVB_T, and PAR
#  33FF = Array size xx, Alltime channels, no TPV, with UVB_Sig, UVB_T, and PAR
#   1FF = Array size xx, Alltime channels w/head_temp and log_volt
#
	    if ($date >= $tpdate) {$tpf = "Y";} # Thermopile (TP) inst flag
	    if ($type eq "mfrsr") {
		if ($init eq "11FF")   {$z =  0;}
		elsif ($init eq "1FF") {$z = -1;}
		elsif ($init eq "101") {$z = -8;}
		else {
		    print "\n                 *** ERROR! ***\n";
		    print " Unexpected init string ($init) in $file\n";
		    print " Expected init strings are: 11FF, 1FF, and 101\n";
		    print " Probably a unique string, so";
		    print " raw files can be moved to a quarantine dir\n\n";
		    die;
		}
	    }
	    if ($type eq "mfr10") {
		if ($init eq "11FF")    {$z = 0;}
		elsif ($init eq "1FF")  {$z = 0;}
		elsif ($init eq "33FF") {$z = 0; $addflds = "Y"}
		elsif ($init eq "73FF") {$z = 1; $addflds = "Y"}
		else {
		    print "\n                 *** ERROR! ***\n";
		    print " Unexpected init string ($init) in $file\n";
		    print " Expected init strings: 11FF, 1FF, 33FF, and 73FF\n";
		    print " Probably a unique string, so";
		    print " raw files can be moved to a quarantine dir\n\n";
		    die;
		}
	    }
	    $ctype = $$rINFO{format};  # Retrieving Format_CAL
	    if ($ctype eq "StdLamp") { 
		my $lamp = $$rINFO{lamp};       # Get lamp SN
	        $rLAMP = get_lamp_data($lamp);  # Load lamp data
	    }
	    next; # Once header file is read go back and read 1st line of data
	}         # End of reading header section

	my @el    = split/\s+/, $_;  # @el is the array that holds tu data
	my $size = scalar @el;

###########################################
# 19700101 - 19000101 = 2208988800 seconds
#
# Using the above constant to simplify time/date calculations.  That
# number is the elapsed seconds between 1 Jan 1900 and 1 Jan 1970.
#
# tu (raw2tu.pl) is configured to output time in LST to be compatible
# with the Langley analysis (la) program.  So below we are accounting 
# for that and first converting to GMT by using $tz from site attributes.
#
	$el[0] = $el[0] - $tz/24;  # Converting to GMT
	my $secs = int($el[0] * 86400 + 0.5)-86400-2208988800;
	my ($ss,$mn,$hh,$dd,$mm,$yyyy) = (gmtime($secs))[0,1,2,3,4,5];
	$yyyy += 1900;
	$mm++;
	my $YYYYMMDD       = sprintf "%4.4d%2.2d%2.2d",$yyyy,$mm,$dd;
	my $YYYYMMDDhhmmss = sprintf "%8d%2.2d%2.2d%2.2d",$YYYYMMDD,$hh,$mn,$ss;
        my @time_formats   = &Time_Calculations ($YYYYMMDDhhmmss);
        my $fYYYYMMDD = $time_formats[1];
        my $fdoy      = $time_formats[2];
        my $fyear     = $time_formats[3];

##########################################
# Uncomment five lines to use included SUNAE code rather than 
# values from tu.  (Note that tu also uses SUNAE).  Will then
# need to comment the corresponding two lines that follow.
#
#	my $cdiy  = $time_formats[4];
#	my $fhr   = $time_formats[5];
#	my @sunae = &SUNAE($yyyy,$cdiy,$fhr,$lat,$lon);
#	my $az    = $sunae[0];
#	my $sza   = 90-$sunae[1];
	my $az    = $el[$size-3];   # Comment if using preceding SUNAE calcs
	my $sza   = $el[$size-1];   # Comment if using preceding SUNAE calcs
	my $csza  = cos(deg2rad($sza));
	my $am    = $el[$size-4];   # Air Mass from tu


##########################################
# Head temperature calculation.  Code taken from Yankee MFRSR cal file.
#
	if ($el[1] > 2000) {
	    $srt = 6810 * (5000 / $el[1] -1);
	    $srt = 1.030852e-3+2.389179e-4 * 
		   log($srt) + 1.574641e-7 * log($srt)**3;
	    $srt = 1.0 / $srt - 273.12;
	} else {
	    $srt = -99.99;
	}

##########################################
# Data logger supply voltage.  Code taken from Yankee MFRSR cal file.
#
	$dlv = $el[9] * 6.0 / 1000.0;


#########################################################################
# First we apply the offsets to the data.  We first assume nighttime
# data have been collected, analyzed, and included in the appropropriate
# calibration file for the site/sensor being processed.  If this hasn't
# happened, then offsets are determined by the algorithm used in
# standard Yankee .CAL files.  This code is not written yet.  Placeholder
# exists.
#
# Apply the offsets to elements of @el.  Note that direct MFRSR values do
# not have nighttime offset data applied as the offset divides out during
# the direct calculation. $z is the array adjustment based on init string.
#
# BASELINE (11FF) INDEXES:  MFR10 ALLTIME channels (2,3,4,5,6,7,8)
#                           MFRSR TOTAL channels   (11,12,13,14,15,16,17)
#                           MFRSR DIFFUSE channels (18,19,20,21,22,23,24)
#                           MFRSR DIRECT channels  (25,26,27,28,29,30,31)
#
	if ($type eq "mfrsr") {
	    foreach my $x (1..7) {
		my $key = "ch".$x; # keys are ch1, ch2...ch7
		if ($el[10+$x+$z] > -999) { # GLOBAL starts w/11: 10+$x
		    $el[10+$x+$z] -= polyeq($srt,$$rOS{$key}); 
		}
		if ($el[17+$x+$z] > -999) { # DIFFUSE starts w/18: 17+$x
		    $el[17+$x+$z] -= polyeq($srt,$$rOS{$key});
		}
	    }
	}

	if ($type eq "mfr10") {
	    foreach my $x (1..7) {
		my $key = "ch".$x; # keys are ch1, ch2...ch7
		if ($el[1+$x] > -999) { # ALLTIME starts with 2, i.e. 1+$x
		    $el[1+$x] -= polyeq($srt,$$rOS{$key});
		}
	    }
	}

# The above offset code assumes nighttime offset data exists.  That is 
# the ideal way to get offset data.  If it doesn't, then use the 
# algorithm given in a standard Yankee .CAL file.
#
# The standard Yankee offset code will go here.
#

#########################################################################
# Below are the sections where calibrations are applied to the data.
# There are several similar sections necessary to account for different
# instrument initializations, e.g. 11FF or 1FF: Different calibration
# methods, e.g. Yankee, Standard Lamp, Langley:  As well as and related
# to if an instrument is a new style with a thermopile broadband channel,
# or an older unit with a silicon broadband detector.
#
# Calibration data are contained in the hash reference $rCAL
#
# Each section checks for: Sensor type $type  (mfrsr/mfr10)
#                          Format_CAL  $ctype (Yankee, StdLamp, Langley)
#                          Thermopile  $tpf   (Y/N)
#
#########################################################################
#  Sensor:     mfrsr
#  Format_CAL: Yankee
#  Thermopile: Y
#
	if (($type eq "mfrsr") && ($ctype eq "Yankee") && ($tpf eq "Y")) {
	    foreach my $x (1..7) {
		my $key  = "ch".$x; # keys are ch1, ch2...ch7

# When key=ch1 produce calibrated BROADBAND values for the MFRSR
# thermopile channel (DIFFUSE, DIRECT, GLOBAL).  This is done in
# SUBROUTINE tp_mfrsr. The method used is from a standard Yankee cal file.
#
		if ($key eq "ch1") {
		    if (($el[10+$x+$z] > -999) &&
			($el[17+$x+$z] > -999) &&
			($el[24+$x+$z] > -999)) { 
			my $bbcal = (@{$$rCAL{$key}})[0]; # BB CAL value
			my $bbscf = (@{$$rCAL{$key}})[1]; # BB Scale Factor
			my $tpg   = ${$$rGAIN{tp}}[0];    # TP gain
			my $tpbos = ${$$rGAIN{tp}}[1];    # TP board offset
			my $bbg   = ${$$rGAIN{$key}}[0];  # Broadband gain
			my $bbdc  = $$rDC{$key};          # Broadband DifCor
			my @tpvals = &tp_mfrsr($el[10],       # TP_HTR CNTS
					       $el[10+$x+$z], # TP_GLOBAL CNTS
					       $el[17+$x+$z], # TP_DIFFUSE CNTS
					       $el[24+$x+$z], # TP_DIRECT CNTS
					       $bbcal,        # BB_Calibration
					       $bbscf,        # BB_Scale_Factor
					       $tpg,          # TP_Gain
					       $tpbos,        # TP_Board_Offset
					       $bbg,          # BB_Gain
					       $bbdc,         # BB_DifCor
					       $csza);        # Cosine_SZA
			$el[17+$x+$z] = $tpvals[0];
			$el[24+$x+$z] = $tpvals[1];
			$el[10+$x+$z] = $tpvals[2];
			next; # Next foreach iteration after tp_mfrsr calc.
		    } else {
			$el[10+$x+$z] = -9999;
			$el[17+$x+$z] = -9999;
			$el[24+$x+$z] = -9999;
		    }
		}
		    
# When key=ch[2,3..7] produce calibrated NARROWBAND MFRSR
# values (GLOBAL, DIFFUSE, DIRECT)
#
# DIFFUSE = (<Offset_Corr_Counts> / (<Cal>*<Gain>)) / <difcor>
# DIRECT  = <Cosine_Corr_Counts> / (<Cal>*<Gain>)
# GLOBAL  = <DIFFUSE> + <DIRECT>*COS_SZA
#
		my $cal  = (@{$$rCAL{$key}})[1]; # 2nd element if not BB
		my $gain = ${$$rGAIN{$key}}[0];  # De-ref array, 1st element
		my $dc   = $$rDC{$key};          # DiffCorr value
		if ($el[17+$x+$z] > -999) {   # Narrow DIFFUSE (19 - 24)
		    $el[17+$x+$z] = ($el[17+$x+$z]/($cal*$gain))/$dc;
		}
		if ($el[24+$x+$z] > -999) {   # Narrow DIRECT (26 - 31)
		    $el[24+$x+$z] = $el[24+$x+$z]/($cal*$gain);
		}
		                              # Narrow GLOBAL (12 - 17)
		if (($el[17+$x+$z] > -999) && ($el[24+$x+$z] > -999)) { 
		    $el[10+$x+$z] = $el[17+$x+$z] + $el[24+$x+$z]*$csza;
		}
	    }
	}



#########################################################################
#   Sensor:     mfrsr
#   Format_CAL: StdLamp
#   Thermopile: N
#
	if (($type eq "mfrsr") && ($ctype eq "StdLamp") && ($tpf eq "N")) {
	    foreach my $x (1..7) {
		my $key  = "ch".$x; # keys are ch1, ch2...ch7

# When key=ch1 produce calibrated BROADBAND values for the 
# MFRSR silicon channel (GLOBAL, DIFFUSE, DIRECT)
#
		if ($key eq "ch1") {
		    if (($el[10+$x+$z] > -999) &&
			($el[17+$x+$z] > -999) &&
			($el[24+$x+$z] > -999)) { 
			my $bbcal = (@{$$rCAL{$key}})[0]; # BB CAL value
			my $bbscf = (@{$$rCAL{$key}})[1]; # BB Scale Factor
			my $bbg   = ${$$rGAIN{$key}}[0];  # Broadband gain
			my $bbdc  = $$rDC{$key};          # Broadband DifCor
			my @tpvals = &si_mfrsr($el[10+$x+$z], # TP_GLOBAL CNTS
					       $el[17+$x+$z], # TP_DIFFUSE CNTS
					       $el[24+$x+$z], # TP_DIRECT CNTS
					       $bbcal,        # BB_Calibration
					       $bbscf,        # BB_Scale_Factor
					       $bbg,          # BB_Gain
					       $bbdc);        # BB_DifCor
			$el[17+$x+$z] = $tpvals[0];
			$el[24+$x+$z] = $tpvals[1];
			$el[10+$x+$z] = $tpvals[2];
			next; # Next foreach iteration after tp_mfrsr calcs.
		    } else {
			$el[10+$x+$z] = -9999;
			$el[17+$x+$z] = -9999;
			$el[24+$x+$z] = -9999;
		    }
		}
		
# When key=ch[2,3..7] produce calibrated NARROWBAND MFRSR
# values (GLOBAL, DIFFUSE, DIRECT)
#
# DIFFUSE: (<Offset_CorCnts> / (<Lamp_On>/1000/<Lamp_Output>*<Gain>)) / <difcor>
# DIRECT:   <Cosine_CorCnts> / (<Lamp_On>/1000/<Lamp_Output>*<Gain>)
# GLOBAL:   <DIFFUSE> + <DIRECT>*COS_SZA
#
		my $cwl  = (@{$$rCAL{$key}})[0]; # Center Wavelength
		my $on   = (@{$$rCAL{$key}})[1]; # Lamp_On value
		my $off  = (@{$$rCAL{$key}})[2]; # Lamp_Off value
		my $val  = $on - $off;           # Lamp_On - Lamp_Off
		my $gain = ${$$rGAIN{$key}}[0];  # De-ref array, 1st element
		my $dc   = $$rDC{$key};          # DiffCorr value
		my $lo   = $$rLAMP{$cwl};        # Lamp Output for $cwl
		
		if ($el[17+$x+$z] > -999) {   # Narrow DIFFUSE (19 - 24)
		    $el[17+$x+$z] = ($el[17+$x+$z]/($val/1000/$lo*$gain))/$dc;
		}
		if ($el[24+$x+$z] > -999) {   # Narrow DIRECT (26 - 31)
		    $el[24+$x+$z] = $el[24+$x+$z]/($val/1000/$lo*$gain);
		}
		                              # Narrow GLOBAL (12 - 17)
		if (($el[17+$x+$z] > -999) && ($el[24+$x+$z] > -999)) { 
		    $el[10+$x+$z] = $el[17+$x+$z] + $el[24+$x+$z]*$csza;
		}
	    }
	}



#########################################################################
#  Sensor:     mfr10
#  Format_CAL: Yankee
#  Thermopile: Y
#
	if (($type eq "mfr10") && ($ctype eq "Yankee") && ($tpf eq "Y")) {
	    foreach my $x (1..7) {
		my $key = "ch".$x;  # keys are ch1, ch2...ch7

# When key=ch1 produce calibrated BROADBAND value for the 
# MFR10 thermopile channel.  This is done in SUBROUTINE tp_mfr10.
# The method used is from a standard Yankee cal file.
#
		if ($key eq "ch1") {
		    if ($el[1+$x] > -999) {
			my $bbcal = (@{$$rCAL{$key}})[0]; # BB CAL value
			my $bbscf = (@{$$rCAL{$key}})[1]; # BB Scale Factor
			my $tpg   = ${$$rGAIN{tp}}[0];    # TP gain
			my $tpbos = ${$$rGAIN{tp}}[1];    # TP board offset
			my $bbg   = ${$$rGAIN{$key}}[0];  # Broadband gain
			my $bbdc  = $$rDC{$key};          # Broadband DifCor
			$el[1+$x] = &tp_mfr10($el[10+$z], # TP_HTR CNTS
					      $el[1+$x],  # BB_GLOBAL CNTS
					      $bbcal,     # BB_Calibration
					      $bbscf,     # BB_Scale_Factor
					      $tpg,       # TP_Gain
					      $tpbos,     # TP_Board_Offset
					      $bbg,       # BB_Gain
					      $bbdc);     # BB_DifCor
			next; # Next foreach iteration after tp_mfrsr calcs
		    } else {
			$el[1+$x] = -9999;
		    }
		}
# When key=ch[2,3..7] produce calibrated NARROWBAND MFR10 values
#
# DIFFUSE = ((<Offset_Corr_Counts> / (<Cal>*<Gain>)) / <difcor>) * <scale_fact>
#
# Lamp_On_Val : mV
# Lamp_Output : W m-2
# Gains       : counts/V
#
		my $cal  = (@{$$rCAL{$key}})[1]; # De-ref array, 2nd element
		my $scf  = (@{$$rCAL{$key}})[3]; # Narrowband Scale Factor
		my $gain = ${$$rGAIN{$key}}[0];  # De-ref array, 1st element
		my $dc   = $$rDC{$key};          # DiffCorr value

		if ($addflds eq "N") {
		    if ($el[1+$x] > -999) {      # Narrow ALLTIME (2 - 8)
			$el[1+$x] = (($el[1+$x]/($cal*$gain))/$dc)*$scf;
		    }
		} else {  # Process additional fields ($addflds = Y)
		    if ($el[1+$x] > -999) {
			$el[1+$x] = (($el[1+$x]/($cal*$gain))/$dc)*$scf;
		    }
#		    $el[10] = &uvb_temp($el[10]);
#		    $el[12]= $el[12]*$calUVB[0]/$calUVB[1];
#		    $el[13]= ($el[13]/237.5)*($calPAR[2]/$calPAR[0])/4.6;
		}
	    }
	}




#########################################################################
#   Sensor:     mfr10
#   Format_CAL: StdLamp
#   Thermopile: N
#
	if (($type eq "mfr10") && ($ctype eq "StdLamp") && ($tpf eq "N")) {
	    foreach my $x (1..7) {
		my $key  = "ch".$x; # keys are ch1, ch2...ch7

# When key=ch1 produce calibrated BROADBAND values for the 
# MFRSR silicon channel (GLOBAL, DIFFUSE, DIRECT)
#
		if ($key eq "ch1") {
		    if ($el[1+$x] > -999) {
			my $bbcal = (@{$$rCAL{$key}})[0]; # BB CAL value
			my $bbscf = (@{$$rCAL{$key}})[1]; # BB Scale Factor
			my $bbg   = ${$$rGAIN{$key}}[0];  # Broadband gain
			my $bbdc  = $$rDC{$key};          # Broadband DifCor
			$el[1+$x] = &si_mfr10($el[1+$x],  # BB CNTS
					      $bbcal,     # BB_Calibration
					      $bbscf,     # BB_Scale_Factor
					      $bbg,       # BB_Gain
					      $bbdc);     # BB_DifCor
			next; # Next foreach iteration after tp_mfrsr calcs
		    } else {
			$el[1+$x] = -9999;
		    }
		}
#zzz
# When key=ch[2,3..7] produce calibrated NARROWBAND MFR10 value
#
# DIFFUSE: (<Offset_CorCnts> / (<Lamp_On>/1000/<Lamp_Output>*<Gain>)) / <difcor>
#
# Lamp_On_Val : mV
# Lamp_Output : W m-2
# Gains       : counts/V
#
		my $cwl  = (@{$$rCAL{$key}})[0]; # Center Wavelength
		my $scf  = (@{$$rCAL{$key}})[3]; # Narrowband Scale Factor
		my $on   = (@{$$rCAL{$key}})[1]; # Lamp_On value
		my $off  = (@{$$rCAL{$key}})[2]; # Lamp_Off value
		my $val  = $on - $off;           # Lamp_On - Lamp_Off
		my $gain = ${$$rGAIN{$key}}[0];  # De-ref array, 1st element
		my $dc   = $$rDC{$key};          # DiffCorr value
		my $lo   = $$rLAMP{$cwl};        # Lamp Output for $cwl
		
		if ($el[1+$x] > -999) {   # Narrow ALLTIME (2 - 8)
		    $el[1+$x] = (($el[1+$x]/($val/1000/$lo*$gain))/$dc)*$scf;
		}
	    }
	}

##########################################
# Begin print statement for outputting data files
#
	if ($type eq "mfr10") {
	    printf OF "%14d %11.5f %14.5f %9.5f %13.8f %7.4f %6.2f %5.2f %7.5f %5.2f %5.2f     %6.1f %7.4f %7.4f %7.4f %7.4f %7.4f %7.4f\n",$YYYYMMDDhhmmss,$el[0],$fYYYYMMDD,$fdoy,$fyear,$am,$az,$sza,$csza,$srt,$dlv,@el[2..8];
	}
	if ($type eq "mfrsr") {
	    printf OF "%14d %11.5f %14.5f %9.5f %13.8f %7.4f %6.2f %5.2f %7.5f %5.2f %5.2f     %7.4f %7.4f %7.4f %7.4f %7.4f %7.4f %7.4f     %7.4f %7.4f %7.4f %7.4f %7.4f %7.4f %7.4f     %7.4f %7.4f %7.4f %7.4f %7.4f %7.4f %7.4f\n",$YYYYMMDDhhmmss,$el[0],$fYYYYMMDD,$fdoy,$fyear,$am,$az,$sza,$csza,$srt,$dlv,@el[11+$z..31+$z];
	}
    }
    close (OF);
    close (IF);
}

##########################################
# Move .cal files to regular directory structure
#
print "\n Move .cal ${path}/cal/<YYYY>\n";
my @callist = `ls *.cal`;     # Need listing of files to extract year
foreach my $calf (@callist) { # Foreach calibration file
    chomp($calf);
    my $yyyy = substr($calf,10,4);
    if (! -e "${path}/cal/${yyyy}") {   # Exist?
	`mkdir -p ${path}/cal/${yyyy}`; # Create
    }
    `mv $calf ${path}/cal/${yyyy}`;
}

# Clean up, remove temporary directory
print "\n rm -rf $tdir\n\n";;
`rm -rf $tdir`;





###################
# SUBROUTINES BELOW
###################


sub uvb_temp () {
    my $uvbtc = shift(@_); # UVB Temp Counts
    my $uvbt;

    
    if ($uvbtc > 400) {
	$uvbt = 6810 * (2500 / $uvbtc - 1);
	if ($uvbt < 1) {$uvbt = 10;} # For bad UVB_Temp values
	$uvbt = 1.030852e-3 + (2.389179e-4 * log($uvbt)) +
	    (1.574641e-7 * log($uvbt)**3);
	$uvbt = 1.0 / $uvbt - 273.12;
    } else {
	$uvbt = -99.99;
    }
    return ($uvbt);
}
1;




sub si_mfr10 () {
############################
# This subroutine makes MFRSR silicon broadband detector data corrections
# and returns corrected values
#
    my $totcnt = shift(@_); # BB counts
    my $cal    = shift(@_); # BB Cal value
    my $scf    = shift(@_); # BB Scale Factor
    my $bbg    = shift(@_); # BB Board gain
    my $dc     = shift(@_); # BB Diffuse Correction

#    print "YO > $totcnt, $cal, $scf, $bbg, $dc\n";
#    sleep 100;
    
    my $CTOT = $totcnt; # For now, no corrections here are applied

    return ($CTOT);
}
1;




sub si_mfrsr () {
############################
# This subroutine makes MFRSR silicon broadband detector data corrections
# and returns corrected values
#
    my $totcnt = shift(@_); # GLOBAL counts
    my $difcnt = shift(@_); # DIFFUSE counts
    my $dircnt = shift(@_); # DIRECT counts
    my $cal    = shift(@_); # BB Cal value
    my $scf    = shift(@_); # BB Scale Factor
    my $bbg    = shift(@_); # BB Board gain
    my $dc     = shift(@_); # BB Diffuse Correction

#    print " > $totcnt, $difcnt, $dircnt\n";
#    print " > $cal, $scf, $bbg, $dc\n";
#    sleep 100;
    
    my $CDIF = $difcnt; # For now, no corrections are applied
    my $CDIR = $dircnt; # For now, no corrections are applied
    my $CTOT = $totcnt; # For now, no corrections are applied

    return ($CDIF,$CDIR,$CTOT);
}
1;




sub tp_mfr10 () {
############################
# This subroutine makes MFRSR thermopile data corrections and
# returns corrected values
#
# NOTE: Generally we can think of "Thermopile" and "Broadband" as
# interchangeable.  The only real distinction comes when considering
# 
#
    my $htrcnt = shift(@_); # Thermopile heater voltage counts
    my $totcnt = shift(@_); # Broadband GLOBAL counts
    my $cal    = shift(@_); # Broadband Calibration value
    my $scf    = shift(@_); # Broadband Scale Factor
    my $tpg    = shift(@_); # Thermopile Board gain
    my $os     = shift(@_); # Thermopile Board offset
    my $bbg    = shift(@_); # Broadband Board gain
    my $dc     = shift(@_); # Broadband Diffuse Correction

#    print "\$htrcnt is: $htrcnt\n";
#    sleep 100;

    my $VHTR = ($htrcnt - $os)/$tpg;
    my $c0 =  1.0023;
    my $c1 =  0.0008769;
    my $c2 = -0.00030897;
    my $c3 =  0.000005350;
    my $CORR = $c0 + ${c1}*$VHTR + ${c2}*${VHTR}**2 + ${c3}*${VHTR}**3;
    my $calcor = $cal / $CORR;  # $calcor = C0A in Yankee .CAL file

    my $d0  = 10.45;
    my $d1  =  0.4177;
    my $d2  =  0.1703;
    my $d3  = -0.02640;
    my $C0B = ($d0 + ${d1}*$VHTR + ${d2}*${VHTR}**2 + ${d3}*${VHTR}**3)/1000;

    my $DIFF = ($totcnt - ($calcor*$bbg) - $os) / ($dc*$cal*$bbg);
    return ($DIFF);
}
1;




sub tp_mfrsr () {
############################
# This subroutine makes MFRSR thermopile data corrections and
# returns corrected values
#
    my $htrcnt = shift(@_); # Thermopile Heater Voltage Counts
    my $totcnt = shift(@_); # Broadband GLOBAL Counts
    my $difcnt = shift(@_); # Broadband DIFFUSE Counts
    my $dircnt = shift(@_); # Broadband DIRECT Counts
    my $cal    = shift(@_); # Broadband Calibration Value
    my $scf    = shift(@_); # Broadband Scale Factor
    my $tpg    = shift(@_); # Thermopile Board Gain
    my $os     = shift(@_); # Thermopile Board Offset
    my $bbg    = shift(@_); # Broadband Board Gain
    my $dc     = shift(@_); # Broadband Diffuse Correction
    my $csza   = shift(@_); # Cosine Solar Zenith Angle

    my $VHTR = ($htrcnt - $os)/$tpg;
    my $c0 =  1.0023;
    my $c1 =  0.0008769;
    my $c2 = -0.00030897;
    my $c3 =  0.000005350;
    my $CORR = $c0 + ${c1}*$VHTR + ${c2}*${VHTR}**2 + ${c3}*${VHTR}**3;
    my $calcor = $cal / $CORR;  # $calcor = C0A in Yankee .CAL file

    my $d0  = 10.45;
    my $d1  =  0.4177;
    my $d2  =  0.1703;
    my $d3  = -0.02640;
    my $C0B = ($d0 + ${d1}*$VHTR + ${d2}*${VHTR}**2 + ${d3}*${VHTR}**3)/1000;

    my $DIFF = ($difcnt - ($C0B*$bbg) - $os) / ($dc*$calcor*$bbg);
    my $DIRN = $dircnt / ($calcor*$bbg);
    my $TOT = ($totcnt - $difcnt)/($calcor*$bbg) + $DIFF;
    my $CDIF = $DIFF * (1.01 + 0.01 * $DIRN/$DIFF);
    my $DIRH = 1.018 * ($TOT - $CDIF);
    my $CDIR = $DIRH/$csza;
    my $CTOT = $CDIF + $DIRH;

    return ($CDIF,$CDIR,$CTOT);
}
1;




sub getdatekey () {
############################
# This subroutine looks at the data date and determines
# the appropriate offset/calibration to use.
#
# There is very likely a more clever way to accomplish
# the task of this subroutine!
#
    my $cmp   = shift(@_);
    my @dates = @_;

    my $num = scalar(@dates);
    if ($num == 0) {die "\n   There are no cal dates to compare!!";}
    my $keydate = -999;
    if ($num > 1) {
	foreach my $i (0..$num-1) {
	    if ( ($cmp >= $dates[$i]) && ($cmp < $dates[$i+1]) ) {
		$keydate = $dates[$i];
	    }
	} 
	if ($keydate == -999) {
	    if ($cmp >= $dates[$num-1]) {
		$keydate = $dates[$num-1];
	    }
	}
    } else {
	if ($cmp >= $dates[0]) {
	    $keydate = $dates[0];
	}
    }
#    print ">$cmp : $keydate => @dates\n";    
    if ($keydate == -999) {
	print "\n Data Date: $cmp\n";
	print " Cal Dates: @dates\n";
	print " No valid calibrations for this input \"Data\" date.\n";
	print " Data date needs to be >= one of the calibration dates.\n";
	die "\n Killed program";
    }
    return ($keydate);
}
1;





sub calibration () {
##########################################################################
# Subroutine calibration gathers the relevant calibration information for 
# the site_instrument from the appropriate calibration file.  This code 
# loads three hashes.  One for the calibration data, and one for the 
# nighttime offset data.  The third hash contains sensor info from the cal
# file (serial number, head hexID, and logger hexID). 
#
# References to each hash are returned to the main program.
#
# Calibration files are located in /home/grad/mfrsr/Calinfo/CAL
# File format is: <site>_<sensor>_<date>.cal
#
#  where site is:    bnd, dra, fpe, etc.
#  sensor is either: mfrsr or mfr10
#  and date is:      YYYYMMDD
#
    my $tli = shift(@_);
    my $type = shift(@_);
    my $date = shift(@_);
    my $tuf  = shift(@_); # Working tu file

# Pull IDs from tu file for later sanity checks against cal file    
    my ($hexb,$hexh,$sn) = (split /_/,$tuf)[3,4,5];
    $sn = (split /\./,$sn)[0];

    my $path = "/home/grad/mfrsr/Calinfo/CAL";
    my @listing = `ls -1 ${path}/${tli}_${type}*.cal`;
    chomp @listing;
    @listing = reverse@listing;

    my $calfile;
  OUTER:
    foreach my $file (@listing) {
        my $caldate = (split '_',$file)[2];  # Extracting date.cal from file
	$caldate = (split '\.',$caldate)[0]; # Returning only date
        if ($caldate <= $date) {
            $calfile = $file;
            last OUTER;
        }
    }

    if (! -f $calfile) { # If file does not exist
        print "\n              *** ERROR! ***\n";
        print " There is no .cal file for ${tli}_${type}_${date}\n";
        print " Check ${path}/ for a .cal file \n\n";
        die;
    }
    
    my $cfn = (split(/\//,$calfile))[-1]; # Return only cal filename
    print "Cal file used is:   $cfn\n";

    open(IF, $calfile) or die "Can't open $calfile: $!\n";

    my $cal_flag    = "N";
    my $off_flag    = "N";
    my $format_flag = "N";
    my (%cal,%offset,%sensinfo);    # Hashes: Calibration and Offset

    while (<IF>) {
	chomp;
	next if /^\s*$/;     # Skip blank lines                             
	next if /^\s*\#/;    # Skip comment lines                           
	s/\#.*$//;           # Strip tag comment                            

	if (/^SN/) {     # Read serial number, add to HASH %sensinfo
	    $sensinfo{sn} = (split/\s+/, $_)[1]; 
	    if ($sensinfo{sn} != $sn) {
		print "\n     ***ERR: May need to create a CAL file!***\n";
		print " The SNs in the cal file and the";
		print " tu file do not match\n";
		print "  -> From ${calfile}:\n";
		print "      SN is: $sensinfo{sn}\n";
		print "  -> Expected based on tu file: $tuf\n";
		print "      SN is: $sn\n\n";
		die;
	    }
	    next;
	}
	if (/^Head/) {   # Read Sensor HexID, add to HASH %sensinfo
	    $sensinfo{hexh} = (split/\s+/, $_)[1]; 
	    $sensinfo{hexh} = substr($sensinfo{hexh},1,4); # Remove $
	    if ($sensinfo{hexh} ne $hexh) {
		print "\n     ***ERR: May need to create a CAL file!***\n";
		print " The head hexIDs in the cal file and the";
		print " tu file do not match\n";
		print "  -> From ${calfile}:\n";
		print "      Head hexID is: $sensinfo{hexh}\n";
		print "  -> Expected based on tu file: $tuf\n";
		print "      Head hexID is: $hexh\n\n";
		die;
	    }
	    next;
	}
	if (/^Logger/) { # Read Logger HexID, add to HASH %sensinfo
	    $sensinfo{hexb} = (split/\s+/, $_)[1]; 
	    $sensinfo{hexb} = substr($sensinfo{hexb},1,4); # Remove $
	    if ($sensinfo{hexb} ne $hexb) {
		print "\n     ***ERR: May need to create a CAL file!***\n";
		print " The logger hexIDs in the cal file and the";
		print " tu file do not match\n";
		print "  -> From ${calfile}:\n";
		print "      Logger hexID is: $sensinfo{hexb}\n";
		print "  -> Expected based on tu file: $tuf\n";
		print "      Logger hexID is: \$$hexb\n\n";
		die;
	    }
	    next;
	}
	if (/^FORMAT/) { # Read calibration format, add to HASH %sensinfo
	    $sensinfo{format} = (split/\s+/, $_)[1]; 
	    if ($sensinfo{format} !~ m/^Yankee|^StdLamp|^Langley/) {
		print "\n                  *** ERROR! ***\n";
		print " There is an error in $calfile\n";
		print " Check line: \"$_\"\n";
		print " It should be set to: Yankee, StdLamp, or Langely";
		print "\n depending on the type of calibration to be used.\n\n";
		die;
	    }
	    if ($sensinfo{format} eq "StdLamp") {$format_flag = "Y";}
	    next;
	}

# Read Lamp serial number if FORMAT_CAL=StdLamp, add to HASH %sensinfo
	if ((/^LAMP_SN/) && ($format_flag eq "Y")) {
	    $sensinfo{lamp} = (split/\s+/, $_)[1]; 
	    if ($sensinfo{lamp} !~ /^\d\d\d\d$/) {
		print "\n                  *** ERROR! ***\n";
		print " There is an error in $calfile\n";
		print " Check line: \"$_\"\n";
		print " It should be set to valid lamp sn, e.g., 1030\n";
		print " Verify the lamp used for this calibration\n\n";
		die;
	    }
	    next;
	}

# Need some sanity code for FORMAT_CAL and LAMP_SN.  If one, then the other
#	if (($sensinfo{format} eq "StdLamp") && ($format_flag eq "N")) {
	    

	if (/^CALI/) {
	    $cal_flag = "Y";
	    next;
	}

	if ($cal_flag eq "Y") {  # Read CALIBRATIONS
	    if (/^OFF/) {        # Exit when OFFSETS encountered
		$cal_flag = "N"; 
		$off_flag = "Y"; 
		next;
	    }
	    my @line = split/\s+/, $_;
	    my $cwl = shift @line;

# 
# Reading in the calibration data for a StdLamp format
#
# THIS CODE IS NOT TRAPPING THE CASE OF A MISSING BB LINE!
#
# AND IS NOT DEALING WITH UVB AND PAR LINES
#
	    if ($sensinfo{format} eq "StdLamp") {
		if ($cwl ne "BB") {
#		print "\$cwl is: $cwl\n";
#		sleep 2;
		    if ((scalar@line < 3) || (scalar@line > 4)) {
			print "\n                     *** ERROR! ***\n";
			print " There is an error in $calfile\n";
			print " with line: \"$cwl   @line\"\n";
			print " When FORMAT_CAL=$sensinfo{format} there";
			print " should be 4 or 5 NARROWBAND fields.\n";
			print " Check the format instructions.\n\n";
			die;
		    } else {
			if (scalar@line == 3) {
			    push @line, 1; # Add scale factor
			}
		    }
		} elsif ($cwl eq "BB") {

#		print "\$cwl is: $cwl\n";
#		sleep 2;
		    my $s = scalar@line;
		    if ((scalar@line < 1) || (scalar@line > 2)) {
			print "\n                     *** ERROR! ***\n";
			print " There is an error in $calfile\n";
			print " with line: \"$cwl   @line\"\n";
			print " When FORMAT_CAL=$sensinfo{format} there";
			print " should be 1 or 2 BB fields.\n";
			print " Check the format instructions.\n\n";
			die;
		    } else {
			if (scalar@line == 1) {
			    push @line, 1; # Add scale factor
			}
		    }
		}
	    }
		

# 
# Reading in the calibration data for a Yankee format
#
	    if ($sensinfo{format} eq "Yankee") {
		if ($cwl ne "BB") {
		    if ((scalar@line < 3) || (scalar@line > 4)) {
			print "\n                     *** ERROR! ***\n";
			print " There is an error in $calfile\n";
			print " with line: \"$cwl   @line\"\n";
			print " When FORMAT_CAL=$sensinfo{format} there";
			print " should be 4 or 5 NARROWBAND fields.\n";
			print " Check the format instructions.\n\n";
			die;
		    } else {
			if (scalar@line == 3) {
			    push @line, 1; # Add scale factor
			}
		    }
		} elsif ($cwl eq "BB") {
		    my $s = scalar@line;
		    if ((scalar@line < 1) || (scalar@line > 2)) {
			print "\n                     *** ERROR! ***\n";
			print " There is an error in $calfile\n";
			print " with line: \"$cwl   @line\"\n";
			print " When FORMAT_CAL=$sensinfo{format} there";
			print " should be 1 or 2 BB fields.\n";
			print " Check the format instructions.\n\n";
			die;
		    } else {
			if (scalar@line == 1) {
			    push @line, 1; # Add scale factor
			}
		    }
		}
	    }
	    

	    my $key;
	    if ($cwl eq "BB") {$key = "ch1";}
	    if ($cwl == 415)  {$key = "ch2";}
	    if ($cwl == 500)  {$key = "ch3";}
	    if ($cwl == 615)  {$key = "ch4";}
	    if ($cwl == 1625) {$key = "ch4";}
	    if ($cwl == 673)  {$key = "ch5";}
	    if ($cwl == 870)  {$key = "ch6";}
	    if ($cwl == 940)  {$key = "ch7";}
#	    print "CAL key is: $key, fields are:  @line\n";
	    $cal{$key} = [ @line ]; # Need @line in square brackets to work
	}

	if ($off_flag eq "Y") {  # Read OFFSETS
	    my (@line) = split/\s+/, $_;
	    my $cwl = shift @line;
	    my $size = scalar @line;
	    while ($size < 5) {
		push @line, 0;
		$size++;
	    }
	    my $key;
	    if ($cwl eq "BB") {$key = "ch1";}
	    if ($cwl == 415)  {$key = "ch2";}
	    if ($cwl == 500)  {$key = "ch3";}
	    if ($cwl == 615)  {$key = "ch4";}
	    if ($cwl == 1625) {$key = "ch4";}
	    if ($cwl == 673)  {$key = "ch5";}
	    if ($cwl == 870)  {$key = "ch6";}
	    if ($cwl == 940)  {$key = "ch7";}
	    $offset{$key} = [ @line ];  # Need @line in square brackets to work
	}
    }

# The offsets in the calibration files are optional.  If no offsets are
# provided they are set to zeros for each channel.  If one or more is
# missing the program dies with an error to check the calibration file.
#
# Filling @offset with zeros.  Order is:
#     Intercept, coef1, coef2, coef3, coef4
#
    my $keynum = keys %offset;
    if ($keynum == 0) {
	foreach my $key (keys %cal) {
	    $offset{$key} = [ (0,0,0,0,0) ]; # Needs the square brackets!!!!
	}
    } elsif (($keynum > 0) && ($keynum < 7)) {
	print "\n                 *** ERROR! ***\n";
	print " We seem to be missing one or more offsets.  There \n";
	print " should be values for each channel, even zeros\n";
	foreach (1 .. 7) {
	    my $key = "ch".$_;
	    if (exists $offset{$key}) {
		print "   $key @{$offset{$key}}\n";
	    } else {
		print "   $key NO VALUES\n";
	    }
	}
	print " Check $calfile for erros/typos\n\n";
	die;
    }
    close (IF);
    return (\%cal, \%offset,\%sensinfo);
}
1;




sub get_lamp_data() {
    my $lamp = shift(@_);
    my $file = "/home/grad/mfrsr/Calinfo/LampData/lamp${lamp}.1.txt";

    open(LD, $file) or die "Can't open $file: $!\n";

    my %lampdata;
    while (<LD>) {
	chomp;
	next if /^\s*$/;     # Skip blank lines                             
	next if /^\s*\#/;    # Skip comment lines                           
	s/\#.*$//;           # Strip tag comment                            
	my ($key,$val) = split,$_;
	$lampdata{$key} = "$val";
    }
    close (LD);

#    for my $k1 (keys %lampdata) {
#	print "$k1\n";
#    }
#    sleep 10;
    return \%lampdata;
}
1;




sub usage {
    use strict;
    print "\n  To run, type \"perl tu2cal.pl <site> <type> <begin_date> <end_date>\"\n\n";
    print "  Site should be one of: bnd, dra, fpe, gwn, ETC\n";
    print "  Type should be either mfrsr or mfr10\n";
    print "  Dates should be in YYYYMMDD format\n\n";
    die;
}
1;



####################################################################
# polyeq produces temperature dependent offsets based on the 
# Head_Temp.  It is capable of using a polynomial fit of up to 
# 5 orders.  If the offset is a pure bias, it merely returns the
# single input value.
# 
# Inputs are temperature and reference to array of 5 coefficients.  
# Higher order coefficients are set to zero if the offset is a simple bias.
#
sub polyeq () {
    my $temp     = shift(@_);
    my $ref_coef = shift(@_); # $$rOS{$key}
    my @coef = @$ref_coef;    # De-reference the array

    if (scalar @coef != 5) {
	print "\n              *** ERROR! ***\n";
	print " polyeq requires 5 coefficient inputs.\n";
	print " Check the calibration subroutine and the calibration file.\n";
	print " Array \@coef has too many coefficients (@coef)\n\n";
	die;
    }
    my $var = $coef[0] + ${coef[1]}*$temp + ${coef[2]}*${temp}**2 +
	      ${coef[3]}*${temp}**3 + ${coef[4]}*${temp}**4;
    return $var;
}
1;


#####################################################################
# Subroutine diffusecorr gathers the diffuse corrections.  
#
sub diffusecorr () {
    use strict;
    my $tli  = shift(@_);
    my $type = shift(@_);
    my $date = shift(@_);
    my $lat  = shift(@_);
    my $tuf  = shift(@_); # Working tu file for sanity checks

# Pull IDs from tu file for later sanity checks against dc file
    my ($hexb,$hexh,$sn) = (split /_/,$tuf)[3,4,5];
    $sn = (split /\./,$sn)[0];

    my $path  = "/home/grad/mfrsr/Calinfo/DiffCorr";
    my @listing = `ls ${path}/${tli}_${type}\*.dc`;
    chomp @listing;
    @listing = reverse sort @listing;

    my $dcfile;
  OUTER:
    foreach my $file (@listing) {
	chomp $file;
	
        my ($dcdate) = (split '_',$file)[2]; 

        if ($dcdate <= $date) {
            $dcfile = $file;
            last OUTER;
        }
    }
    if (! -f $dcfile) {
        print "\n                 *** ERROR! ***\n";
        print " There is no DiffCorr (.dc) file for use with date $date\n";
        print " Check ${path}/ for a .dc file \n\n";
        die;
    }
    
    my $hem;
    if ($lat >= 0) {
	$hem = "NORTHERN";
    } else {
	$hem = "SOUTHERN";
    }

    my $hf = "N";   # Hemisphere Flag initialized to No
    my %dc;

# Extract head and board ID info from .dc file for sanity check against .tu file
    my ($hb,$hh,$s) = (split /_/,$dcfile)[3,4,5];
    $s = (split /\./,$s)[0]; # Remove .dc extension

    if ($sn != $s) {  # Compare SNs
	print "\n     ***ERR: May need to create a .dc file!***\n";
	print " The SNs in the dc file and the";
	print " tu file do not match\n";
	print "  -> From ${dcfile}:\n";
	print "      SN is: $s\n";
	print "  -> Expected based on tu file: $tuf\n";
	print "      SN is: $sn\n\n";
	die;
    }
	
    if ($hexh ne $hh) {  # Compare hex Head IDs
	print "\n     ***ERR: May need to create a .dc file!***\n";
	print " The hex Head IDs in the dc file and the";
	print " tu file do not match\n";
	print "  -> From ${dcfile}:\n";
	print "      hexh is: $hh\n";
	print "  -> Expected based on tu file: $tuf\n";
	print "      hexh is: $hexh\n\n";
	die;
    }
	
    if ($hexb ne $hb) {  # Compare hex Logger IDs
	print "\n     ***ERR: May need to create a .dc file!***\n";
	print " The hex Logger IDs in the dc file and the";
	print " tu file do not match\n";
	print "  -> From ${dcfile}:\n";
	print "      hexb is: $hb\n";
	print "  -> Expected based on tu file: $tuf\n";
	print "      hexb is: $hexb\n\n";
	die;
    }
	
    open (IF, $dcfile) or die "Can't open $dcfile: $!\n";
    while (<IF>) {
	chomp;
	if (/^$hem/) {
	    $hf = "Y";
	    next;
	}
	
	if ($hf eq "Y") {
	    if (/^END/) {
		last;
	    }
	    my ($ch,$val) = (split /\s+/, $_)[1,3];
	    my $key = "ch".$ch;
	    $dc{$key} = $val
	}
    }
    return \%dc; # Return hash reference
}
1;




#####################################################################
# Subroutine loggergains gathers logger gain information
#
sub loggergains () {
    my $hexb = shift(@_);

    my $path = "/home/grad/mfrsr/Calinfo/LoggerGains";
    my $file = "${path}/${hexb}";
    if (! -f $file) {
	print "\n              *** ERROR! ***\n";
	print " There is no logger gain file for $hexb\n";
	print " Check $path\n\n";
	die;
    }

    open(LG, $file) or die "Can't open $file: $!\n";

    my %gain;
    while (<LG>) {
	chomp;
	next if /^\s*$/;     # Skip blank lines                             
	next if /^\s*\#/;    # Skip comment lines                           
	s/\#.*$//;           # Strip tag comment                            

	my @line = split, split/\s+/, $_;
	if (scalar @line == 2) {
	    push @line, 0;   # Add zero offset if not given
	}
	my $cwl = shift @line;
	my $key;
	if ($cwl eq "BB") {$key = "ch1";}
	if ($cwl == 415)  {$key = "ch2";}
	if ($cwl == 500)  {$key = "ch3";}
	if ($cwl == 615)  {$key = "ch4";}
	if ($cwl == 1625) {$key = "ch4";}
	if ($cwl == 673)  {$key = "ch5";}
	if ($cwl == 870)  {$key = "ch6";}
	if ($cwl == 940)  {$key = "ch7";}
	if ($cwl eq "TP") {$key = "tp";}
	$gain{$key} = [ @line ];
    }
    close (LG);

#    for my $k1 (keys %gain) {
#	print "$k1\n";
#    }
#    sleep 10;
    return \%gain;
}
1;











__END__

#	for my $k1 (sort keys %$rOS) {
#	    print "$k1\n";
#	    for my $k2 ( sort{$rank{$a} <=> $rank{$b}} keys %{$rOS->{$k1}} ) {
#		my @flds = split /\s+/,$rOS->{$k1}->{$k2};
#		my $n = scalar@flds;
#		print ">$k2 $n @flds\n";
#	    }
#	}

#	for my $k1 (sort keys %$rCAL) {
#	    print " $k1\n";
#	    for my $k2 ( sort{$rank{$a} <=> $rank{$b}} keys %{$rCAL->{$k1}} ) {
#		my @flds = split /\s+/,$rCAL->{$k1}->{$k2};
#		my $n = scalar@flds;
#		print ">>$k2 $n @flds\n";
#	    }
#	}
	
	
	
sub determine_dates () {
    use strict;
    use Time::DaysInMonth;

    my $start = shift(@_);
    my $end   = shift(@_);

    $start =~ /(\d\d\d\d)(\d\d)(\d\d)/;
    my $beg_y = $1;
    my $beg_m = $2;
    my $beg_d = $3;
    
    $end   =~ /(\d\d\d\d)(\d\d)(\d\d)/;
    my $end_y = $1;
    my $end_m = $2;
    my $end_d = $3;

    my $year_calc  = (($end_y - $beg_y)*12);
    my $num_months = (($end_m + $year_calc) - $beg_m) + 1; # Num of months

    my $cnt  = 1;
    my $year = $beg_y;
    my $mon  = $beg_m;
    my @YYYYMM = ();
    while ($cnt < ($num_months + 1)) {
	if ($mon == 13) {
	    $year++;
	    $mon = 1;
	}
	push @YYYYMM, (($year*100)+$mon);
	$mon++;
	$cnt++;
    }

    my @dates;
    my $chk = "Y";
    foreach (@YYYYMM) {
	my ($cnt,$dim);
	
# Setting the first YYYYMMDD days to begin_days	
	if ($chk eq "Y") {
	    $cnt = $beg_d;
	    $chk = "N";
	} else {
	    $cnt = 1;
	}

	my $yyyy = substr($_,0,4);
	my $mm   = substr($_,4,2);

# Setting days_in_month (dim) based on YYYYMM or end_days
	if ( (($yyyy*100)+$mm) != (($end_y*100)+$end_m) ) {
	    $dim = days_in($yyyy,$mm);
	} else {
	    $dim = $end_d;
	}

	while ($cnt < $dim+1) {
	    push @dates, (($yyyy*10000)+($mm*100)+$cnt);
	    $cnt++;
	}
    }
    return @dates;
}
1;


sub check_site () {
    use strict;
#    use Text::Abbrev;
    my @all_sites = qw/bnd dra fpe gwn psu sxf tbl twr lab/;
    my $site = shift(@_);

    if ($site !~ /bnd|dra|fpe|gwn|psu|sxf|tbl|twr|lab/) {
	die "\n  $site does not match any site.  Check";
    }
	
	
#    my %site_codes = abbrev @all_sites;

#    my $tli = $site_codes{$site};
# || (input=~/^\d+$/ && $input<=$#all_sites && $all_sites[$input]);

#    if (! $tli) {
#	die "\n$site does not match any site.  Check";
#    }
    
}
1;


sub check_dates () {
    use strict;
    use Time::DaysInMonth;

    my $start = shift(@_);
    my $end   = shift(@_);

    my $days;

    if ($start !~ /^\d{8}$/) {
	die "\nStart date $start must be in YYYYMMDD format";
    }
    if ($end !~ /^\d{8}$/) {
	die "\nEnd date $end must be in YYYYMMDD format";
    }

    if ($end < $start) {die "\nStart date must be before or equal to end date";}

    $start =~ /(\d\d\d\d)(\d\d)(\d\d)/;
    my $beg_y = $1;
    my $beg_m = $2;
    my $beg_d = $3;
    
    $end   =~ /(\d\d\d\d)(\d\d)(\d\d)/;
    my $end_y = $1;
    my $end_m = $2;
    my $end_d = $3;

    if ($beg_y < 1990) {
	die "Begin year $beg_y out of range.  Check";
    }
    if ($end_y > 2100) {
	die "End year $end_y out of range.  Check";
    }

    if ($beg_m < 1 || $beg_m > 12) {
	die "Begin month $beg_m out of range.  Check";
    }
    if ($end_m < 1 || $end_m > 12) {
	die "End month $end_m out of range.  Check";
    }
    
    $days = days_in($beg_y,$beg_m); # Calculating number days in begin YYYYMM
    if ($beg_d < 1 || $beg_d > $days) {
	die "\nBegin day $beg_d out of range.  There are $days days in $beg_y$beg_m";
    }

    $days = days_in($end_y,$end_m); # Calculating number days in end YYYYMM
    if ($end_d < 1 || $end_d > $days) {
	die "\nEnd day $end_d out of range.  There are $days days in $end_y$end_m";
    }
}
1;


###############################################################################
# Subroutine sunae
#
# Calculates the Azimuth, Elevation, Solar Distance and Disk Diameter
#
# Fixed some errors in the refraction code on 20111108
#
###############################################################################
sub SUNAE () {
    use Math::Trig;
#    use strict;
    my $year = shift(@_);
    my $day  = shift(@_);
    my $hour = shift(@_); # Fractional hour
    my $lat  = shift(@_);
    my $long = shift(@_);

    my ($refrac);

    if ($year < 1950 || $year > 2050) {
        die "SUNAE--bad input variable YEAR ($year), stopped\n";
    }
    if ($day < 1 || $day > 366) {
        die "SUNAE--bad input variable DAY ($day), stopped\n";
    }
    if ($hour < -13.0 || $hour > 36.0) {
        die "SUNAE--bad input variable HOUR ($hour), stopped\n";
    }
    if ($lat < -90 || $lat > 90) {
        die "SUNAE--bad input variable LAT ($lat), stopped\n";
    }
    if ($long < -180 || $long > 180) {
        die "SUNAE--bad input variable LON ($long), stopped\n";
    }

    my $pi    = atan2(1,1) * 4;
    my $twopi = 2.0 * $pi;
    my $rpd   = $pi/180;

#                    ** current Julian date (actually add 2,400,000
#                    ** for true JD);  LEAP = leap days since 1949;
#                    ** 32916.5 is midnite 0 jan 1949 minus 2.4e6

    my $delta = $year - 1949;
    my $leap  = int($delta / 4);
    my $jd = 32916.5 + ($delta*365 + $leap + $day) + ($hour/24.);
#
#                    ** last yr of century not leap yr unless divisible
#                    ** by 400 (not executed for the allowed YEAR range,
#                    ** but left in so our successors can adapt this for
#                    ** the following 100 years)


    if (($year % 100 == 0) && ($year % 400 != 0)) {
        $jd = $jd - 1;
    }

#                     ** ecliptic coordinates
#                     ** 51545.0 + 2.4e6 = noon 1 jan 2000

    my $time = $jd - 51545.0;

#                    ** force mean longitude between 0 and 360 degs

    my $mnlong = 280.460 + (0.9856474 * $time);
#    $mnlong = ($mnlong % 360);
    while ($mnlong > 360) { $mnlong = $mnlong - 360; }

#                    ** mean anomaly in radians between 0 and 2*pi

    my $mnanom = 357.528 + (0.9856003 * $time);
#    $mnanom = ($mnanom % 360);
    if ($mnanom < 0) { $mnanom = $mnanom + 360; }
    $mnanom = $mnanom * $rpd;

#                    ** ecliptic longitude and obliquity
#                    ** of ecliptic in radians

    my $eclong = $mnlong + 1.915*sin($mnanom) + 0.020*sin(2*$mnanom);
    while ($eclong > 360) { $eclong = $eclong - 360; }

    my $oblqec = 23.439 - 0.0000004*$time;
    $eclong = $eclong*$rpd;
    $oblqec = $oblqec*$rpd;

#                    ** right ascension

    my $num  = cos($oblqec)*sin($eclong);
    my $den  = cos($eclong);
    my $temp = $num/$den;
    my $ra   = atan($num/$den);

#                    ** Force right ascension between 0 and 2*pi

    if ($den < 0) {
        $ra  = $ra + $pi;
    } elsif ($num < 0) {
        $ra  = $ra + $twopi;
    }

#                    ** declination

    my $dec = asin(sin($oblqec)*sin($eclong));

#                    ** Greenwich mean sidereal time in hours

    my $gmst = 6.697375 + 0.0657098242*$time + $hour;

#                    ** Hour not changed to sidereal time since
#                    ** 'time' includes the fractional day

    while ($gmst > 24) { $gmst = $gmst - 24; }

#                    ** local mean sidereal time in radians

    my $lmst  = $gmst + $long/15;
    while ($lmst > 24) { $lmst = $lmst - 24; }
    $lmst   = $lmst * 15 * $rpd;

#                    ** hour angle in radians between -pi and pi

    my $ha  = $lmst - $ra;
    if ($ha < -$pi) { $ha  = $ha + $twopi; }
    if ($ha > $pi) { $ha  = $ha - $twopi; }

#                    ** solar azimuth and elevation

    my $el = asin(sin($dec) * sin($lat * $rpd) +
               cos($dec) * cos($lat * $rpd) * cos($ha));

    my $az = asin(-cos($dec) * sin($ha) / cos($el));

#                    ** Put azimuth between 0 and 2*pi radians

    if ((sin($dec) - sin($el) * sin($lat * $rpd)) > 0) {
        if (sin($az) < 0) { $az = $az + $twopi; }
    } else {
        $az = $pi - $az;

    }

#                     ** Convert elevation and azimuth to degrees
    $az  =  $az / $rpd;
    $el  =  $el / $rpd;

#  ======== Refraction correction for U.S. Standard Atmos. ==========
#      (assumes elevation in degs) (3.51823=1013.25 mb/288 K)

    if ($el > 19.225 ) {
        $refrac = 0.00452*3.51823 / tan($el*$rpd);
    } elsif ($el > -0.766 && $el < 19.225 ) {
        $refrac = 3.51823 * (0.1594 + 0.0196*$el + 0.00002*$el**2) /
            (1 + 0.505*$el + 0.0845*$el**2);

    } elsif ($el <= -0.766 ) {
        $refrac = 0.0;
    }
    $el = $el + $refrac;

# ===================================================================

#                   ** distance to sun in A.U. & diameter in degs

    my $soldst = 1.00014 - 0.01671*cos($mnanom) - 0.00014*cos(2*$mnanom);
    my $soldia = 0.5332 / $soldst;

    if ($el < -90 || $el > 90) {
        die "SUNAE--Output argument EL ($el) out of range\n";
    }
    if ($az < 0 || $az > 360) {
        die "SUNAE--Output argument AZ out of range\n";
    }
    my @returnary = ($az, $el, $soldst, $soldia);
    return (@returnary);
}
1;


