#!/usr/bin/perl
#
# The input .tu file should be generated by:
#  tu -d joe -r start -z <tz> -x maez -c <solfile> -H -o <output_file> file.mtm
#
# To run:  perl tu2la.pl <site> <start_date> <end_date>
#
use strict;
use Time::Local;

# Home-brewed and other modules that are common to multiple programs.
use lib "/home/grad/mfrsr/bin";
use Modules::Check_Site;
use Modules::Check_Dates;
use Modules::Determine_Dates;
use Modules::Site_Information;
use Modules::Time_Calculations;
use Modules::SUNAE;
use Statistics::R;

# Make sure it is user mfrsr running the program
my $user = getlogin();
if ($user !~ /^mfrsr/) {
    print "\n Derp! You are running as user: $user\n";
    print " This program needs to be run by user \'mfrsr\' in order";
    print " to create\n the directories and files with proper ownership.\n";
    die "\n";
}

if (scalar@ARGV != 3) {&usage();}
my $site  = $ARGV[0];
my $start = $ARGV[1];
my $end   = $ARGV[2];
my $type  = "mfrsr";  # Setting type to mfrsr rather than use ARGV

&Check_Site($site);        # Make sure site is valid
&Check_Dates($start,$end); # Make sure dates are valid
my @dates = &Determine_Dates($start,$end);


############################################################################
# Gather site attributes from site_info file.  Necessary to determine site
# type (mfrsr or tower), and for lat/lon if using SUNAE code
#
my @siteinfo = &Site_Information($site,$type); # Ret lat, lon, tz, new_date
my $lat    = $siteinfo[0];
my $lon    = $siteinfo[1];
my $tz     = $siteinfo[2];

############################################################################
# Copy .tu files for date range requested into temp directory, and then 
# cd to that directory.  Includes check for existence of files to process.
#
my $tempdir = "/tmp/mfrsr_la_proc";
`rm -rf $tempdir`;
`mkdir $tempdir`;

print "\n  Copying files to $tempdir\n\n";
my $path = "/u6/mfrsr/${site}/${type}/tu";
foreach my $date (@dates) {
    `cp ${path}/${site}_${type}_${date}*\.tu $tempdir/`;
}

my @files = `ls ${tempdir}/\*.tu`;
if (scalar @files == 0) {die "\nNo .tu files to process";}


############################################################################
# Begin loop to process each file.
#
my $out = "${tempdir}/${site}_${start}_${end}_la.out";       # la output file
my $cfg = "/home/grad/mfrsr/Calinfo/Langley/${site}_la.cfg"; # la config file
if (! -f $cfg) { # If file does not exist
    print "              *****  ERROR  *****\n\n";
    print "The config file: $cfg\n";
    print "does not exist.\n\n";
    die;
}

# Running la on each day and dumping output to $out
foreach my $file (@files) {
    chomp $file;
    print STDOUT "Processing tu file: $file\n";
    `la -n 1 -f $cfg $file >> $out`;
}
#`rm -rf $tempdir/\*.tu`; # Deleting tu files in temp directory

# Clean up la output ($out) leaving only dates when V0s were produced
my $clean = "${tempdir}/${site}_${start}_${end}_la.clean";  # la output, clean
`grep -v points $out | grep -B1 -A4 'Channel   1' | grep -v '^--' > $clean`;

my $la_date = "${tempdir}/${site}_${start}_${end}_la.date"; # V0 dates
my $la_hour = "${tempdir}/${site}_${start}_${end}_la.hour"; # V0 hours
my $la_v0s  = "${tempdir}/${site}_${start}_${end}_la.v0s";  # V0s


# A series of greps, cuts, seds to strip the cleaned-up la output for 
# separate files to be used as input to Joe's R code.
#
`grep Time $clean | cut -d " " -f3 > $la_date`;
`grep Time $clean | cut -d " " -f7 | cut -d ":" -f1 > $la_hour`;
`grep Channel $clean | sed 's/    / /g' | sed 's/   / /g' | sed 's/  / /g' | cut -d " " -f4 > $la_v0s`;

# Add check if no V0s found, produce message
if (-z $la_v0s) { # -z tests for empty file
    print "\n\n At $site from $start - $end there were no valid Langleys.\n\n";
    print " Consider expanding the input time range.\n\n";
    exit 1; # Exits without message
}

# Convert MM/DD/YYYY in $la_date to fractional days since 1970 (MFRSR time)
my $la_jd = "${tempdir}/${site}_${start}_${end}_la.jd";
open(OF, ">$la_jd");
`jd -f $la_date > $la_jd`;
close(OF);

# Determine last jd of prior year
my $p_yyyy = substr($start,0,4) - 1;  # $p_yyyy is prior year based on $start
my $jd_prior = `jd "12\/31\/$p_yyyy"`;

############################################################
# Calls to Joe's R code.  The following lines are modeled after his
# get_v0s.f function.  It produces a matrix of V0s.
#
my $R = Statistics::R->new();  # Starting R

# These will be fractional days since 1900 (Excel time) -1 day
$R->run(qq `jd <- scan("$la_jd")`);

# This is the last hour of the range for each Langley
$R->run(qq `hr <- scan("$la_hour")`);

# Adjusting for time tone (subtract 7 hours for MST)
# $tz is read from station attributes above
$R->run(qq `hr <- hr + $tz`);

# End time between 11 & 13.  This is the AM Langley
$R->run(qq `hr[hr >= 11 & hr < 13] <- 0.25`);

# End time less than 1 AM.  This is the PM Langley
$R->run(qq `hr[hr < 1 & hr != 0.25] <- 0.75`);

# These two lines create rows of V0s in channel order	
$R->run(qq `dat <- scan("$la_v0s")`);
$R->run(qq `data <- matrix(dat, ncol = 5, byrow = T)`);

# Need to ask Joe what is happening here.
$R->run(qq `v0s <- cbind(jd - $jd_prior + hr, data)`);

# Outputting V0s and storing in $v0s
my $v0s = $R->run(qq `print(v0s)`);
$R->stop; # Stopping R

my $ucsite = uc$site;
print "\n  Matrix of V0s for $ucsite from ${start}-${end}\n\n";
print "$v0s\n\n";

# Need to get V0 output into a file
my @v0s = (split/\n/, $v0s); # Split $v0s on newline chars
my $v0s_mtx  = "${tempdir}/${site}_${start}_${end}_la.mtx";  # V0s mtx
open(OF, ">", "$v0s_mtx");
foreach (@v0s) {
    print OF "$_\n";
}
close(OF);

#########################################
# Below commented for testing purposes
#
#&plot_v0s(); # Calling subroutine plot_v0s

my $nlines = `wc -l < $v0s_mtx`;
chomp($nlines);
my @lowfits;
if ($nlines > 20) {          # v0s_estimate needs at least 20 v0s to run
    @lowfits = &v0s_estimate($v0s_mtx); # Calling subroutine v0s_estimate
                                        # Returns array of lowess fits for
                                        # 415, 500, 615, 673, 870, 940
} else {
    print "\n                       ***** ERROR *****\n\n";
    print " There are not enough v0s to run v0s_estimate.  At least 20\n";
    print " v0s are required.  Expand the date range $start - ${end}.\n\n";
    die;
}




&cloudscreened(@lowfits,$tempdir);



############################################################
# Subroutines below
############################################################

############################################################
# Calls to Joe's R code.  The following lines are modeled after his
# cloudscreened.f function.
#
sub cloudscreened() {
    use strict;
    my $low415  = $_[0];
    my $low500  = $_[1];
    my $low615  = $_[2];
    my $low673  = $_[3];
    my $low870  = $_[4];
    my $tempdir = $_[5];


    my @files = `ls ${tempdir}/\*.tu`;
    foreach my $file (@files) {
	chomp $file;
	my $fn = (reverse(split/\//,$file))[0];  # Returns only filename, not path
	my ($date,$sn) = (split/_|\./,$fn)[2,5]; # Split on _ or . Returns date and SN
	print "$file\n";
	$R->run (qq `file <- matrix(scan("${file}", skip = 1), ncol = 36, byr = T)
	             if (length(file) == 0) {
	                 return()
	             }
	             file <- file[file[, 33] < 6 & file[, 33] > 1, ]
	             if (length(file) == 0) {
		         return()
	             }
	             for (i in 27:31) {
	                file <- file[file[, i] > 0, ]
		        if (length(file) == 0 | length(file) == 36) {
		            return()
	                }
	             }`);
	my @alphaoz = &alphaozeff($date,$sn,$tempdir);

    }
    $R->stop; # Stopping R
    print "\n\n      MADE IT HERE!!!!!!!!!!\n\n\n";
}
1;

############################################################
# Calls to Joe's R code.  The following lines are modeled after his
# cloudscreened.f function.
#
sub alphaozeff() {
    use strict;
    my $date    = $_[0];
    my $sn      = $_[1];
    my $tempdir = $_[2];
    
    my $path = "/home/grad/mfrsr/Calinfo/FilterProfiles";
    my @list = `ls -1 ${path}/${sn}_????_????????_????.spr`;
    chomp @list;
    @list = reverse@list;

# Identify appropriate filter_profile file to be used with tu file
    my $filtfile;
  OUTER:    
    foreach my $file (@list) {
        my $fn = reverse(split/\//,$file); # Return filename only
	my $fndate = (split /_/,$fn)[2];   # Return only date
        if ($fndate <= $date) {
            $filtfile = $file;
            last OUTER;
        }
    }

# Now need to make sure filtfile is in the expected format
    my $header = `head -1 $filtfile`;
    my @head   = split /\s+/,$header;
    my @filtfunc;
    if (scalar@head < 10) { # A Yankee file has 10 columns
	open (FF, "<$filtfile") or die "Can't open $filtfile : $!";
	my $flag = "Y";
	while (<FF>) {
	    chomp;
	    next if /^\s*$/;  # Skip blank lines
	    if (($_ !~ /^3/) && ($flag eq "Y")) { # Search for start of data
		next;
	    }
	    $flag = "N";
	    my @el = split /\s+/,$_;
	    my $line = sprintf "%6.1f %8.5f %8.5f %8.5f %8.5f %8.5f",$el[0],@el[2..6];
	    push (@filtfunc, $line);
	}
	print "\nContents of \@filtfunc are:\n";
	foreach my $line (@filtfunc) {

	    print ">$line\n";
	}
	close (FF);
    } else {  # When scalar@head = 10, so a Yankee filter file
	open (FF, "<$filtfile") or die "Can't open $filtfile : $!";
	while (<FF>) {
	    chomp;
	    next if /^\s*$/;  # Skip blank lines
	    my @el = split /\s+/,$_;
	    my $line = sprintf "%6.1f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f",$el[0],$el[1],@el[5..9];
	    push (@filtfunc, $line);
	}
	print "\nContents of \@filtfunc are:\n";
	foreach my $line (@filtfunc) {
	    print "<$line\n";
	}
	close (FF);
    }   
	
    


    print "\nIn subroutine alphaozeff\n";
    print "\$date is: $date\n";
    print "\$sn is:   $sn\n\n";
    print scalar@head;
    print "\n\$filtfile is: $filtfile\n";

}
1;


############################################################
# Calls to Joe's R code.  The following lines are modeled after his
# vos_estimate.f function.
#
sub v0s_estimate {
    my $input_file = shift(@_); # This is the data matrix ($v0s_mtx)
#    print "\$input_file is: $input_file\n";

    my $R  = Statistics::R->new();  # Starting R
    my $c1 = 3;
    my $c2 = 6;
    my $f  = 0.3; # Change to f = (lastT - FirstT)/90
    $R->run('x11()');

    $R->run(qq `file <- read.table("${input_file}")`);

    $R->run(qq `forgan <- NULL`);
    
# Assumes data taken after 2009
    $R->run(qq `file[, 1] <- file[, 1] + 40177`);

# Use langleys 1-20, 2-21, ...
# "temp" gets the middle ratios
# "forgen" gets mean of inner quartile range
    $R->run(qq `for (i in 1:(length(file[, 1]) - 19)) {
                foo20  <- file[i:(i + 19), ]
                foo    <- boxplot.stats(foo20[, ${c1}]/foo20[, ${c2}])\$stats
                temp   <- foo20[foo20[, ${c1}]/foo20[, ${c2}] >= foo[2] &
                          foo20[, ${c1}]/foo20[, ${c2}] <= foo[4], ]
                forgan <- rbind(forgan, apply(temp, 2, mean)) }`);
    
    $R->run(qq `end <- dim(forgan)[1]`); # Find number of rows in the file

# Prepending points before first row and appending points after last row
    $R->run(qq `forgan2 <- rbind(file[file[, 1] < forgan[1, 1], ], forgan, file[file[, 1] > forgan[end, 1], ])`);

    $R->run(qq `for (j in 2:6) { # plot all points in file, then the forgan points, then lowess thru modified forgan points
                    plot(file[, 1], file[, j], pch = 20)
                    points(forgan[, 1], forgan[, j], pch = 20, col = 2)
                    title(j)
                    low <- lowess(forgan2[, 1], forgan2[, j], ${f})
                    abline(lsfit(forgan2[, 1], forgan2[, j]), col = 6) # add linear fit to show overall trend
                    lines(low, col = 2, lwd = 2)
                    system("sleep 1")
                    #browser()
                    if (j == 2) {
                        low415 <<- low # save lowess fit for each filter
                    }
                    if (j == 3) {
                        low500 <<- low
                    }
                    if (j == 4) {
                        low615 <<- low
                    }
                    if (j == 5) {
                        low673 <<- low
                    }
                    if (j == 6) {
                        low870 <<- low
                    }
                }`);
    
    my @lowfits;
    $lowfits[0] = $R->run (qq `print(low415)`); 
    $lowfits[1] = $R->run (qq `print(low500)`); 
    $lowfits[2] = $R->run (qq `print(low615)`); 
    $lowfits[3] = $R->run (qq `print(low673)`); 
    $lowfits[4] = $R->run (qq `print(low870)`); 
    return (@lowfits);


    $R->stop; # Stopping R
}
1;




############################################################
# Calls to Joe's R code.  The following lines are modeled after his
# plot_v0s.f function.
#
sub plot_v0s {
    my $R = Statistics::R->new();
    my $c1 = 3;
    my $c2 = 6;
    
    $R->run('x11()');
    
    $R->run(qq `matrix <- read.table("${v0s_mtx}")`);
    
    $R->run(qq `plot(matrix[, 1], matrix[, ${c1}]/matrix[, ${c2}], type = "n")`);
    
    $R->run(qq `text(matrix[, 1], matrix[, ${c1}]/matrix[, ${c2}], label = 1:length(matrix[,1]))`);
    
    $R->run(qq `foo <- boxplot.stats(matrix[, ${c1}]/matrix[, ${c2}])\$stats`);
    
    $R->run(qq `temp <- matrix[matrix[, ${c1}]/matrix[, ${c2}] >= foo[2] & matrix[, ${c1}]/matrix[, ${c2}] <= foo[4], ]`);
    
    $R->run(qq `points(temp[, 1], temp[, ${c1}]/temp[, ${c2}], pch = 20, col = 2, cex = 0.5)`);
    
    $R->run(qq `abline(h = foo[c(2, 4)], col = 2)`);
    
    $R->run(qq `abline(h = foo[3], lty = 2, col = 3)`);
    
    my $mean   = $R->run(qq `print(apply(temp[, c(2, 3, 4, 5, 6)], 2, mean))`);
    
    my $medqtr = $R->run(qq `print(apply(temp[, c(2, 3, 4, 5, 6)], 2, median))`);
    
    my $medall = $R->run(qq `print(apply(matrix[, c(2, 3, 4, 5, 6)], 2, median))`);
    
# Print the uncertainty in V0
    my $uncert  = $R->run(qq `print(sqrt(apply(temp[, c(2, 3, 4, 5, 6)], 2, var))/sqrt(length(temp[, 1])))`);

# Print the fractional uncertainty in V0
    my $uncertf = $R->run(qq `print(sqrt(apply(temp[, c(2, 3, 4, 5, 6)], 2, var))/sqrt(length(temp[, 1]))/apply(temp[, c(2, 3, 4, 5, 6)], 2, mean))`);
    
    my @mean    = split /\s+/, $mean;
    my @medqtr  = split /\s+/, $medqtr;
    my @medall  = split /\s+/, $medall;
    my @uncert  = split /\s+/, $uncert;
    my @uncertf = split /\s+/, $uncertf;

    printf "\n                %5s     %5s     %5s     %5s     %5s\n",@mean[1..5];
    printf "MEAN         %8.3f  %8.3f  %8.3f  %8.3f  %8.3f\n",@mean[6..10];
    printf "MEDIUM QTR   %8.3f  %8.3f  %8.3f  %8.3f  %8.3f\n",@medqtr[6..10];
    printf "MEDIUM ALL   %8.3f  %8.3f  %8.3f  %8.3f  %8.3f\n",@medall[6..10];
    printf "UNCERTAINTY  %8.3f  %8.3f  %8.3f  %8.3f  %8.3f\n",@uncert[6..10];
    printf "FRAC UNCERT  %8.3f  %8.3f  %8.3f  %8.3f  %8.3f\n\n",@uncertf[6..10];

    print "Press ENTER to exit:";
    <STDIN>;

    $R->stop; # Stopping R
}
1;

###########################################################################
# Subroutine usage.  Gives instructions on how to run if number of command
# line arguments are not valid
sub usage {
    use strict;
    print "\n  To run, type \"perl tu2la.pl <site> <begin_date> <end_date>\"\n\n";
    print "  Site should be one of: bnd dra fpe gwn psu sxf tbl\n";
    print "  Dates should be in YYYYMMDD format\n\n";
    die;
}
1;





__END__
`R --save<< EOF`
EOF





my $cmds = <<EOF;

a <- 2
b <- 5
c <- a * b
print('ok')
EOF

$R->run($cmds);
#my $out2 = `$R->run($cmds)`;

print "R >>> $cmds\n\n";








my $out = $R->run( q`print( 1 + 2 )` );

print "<>\n$out\n";

my $cmds = <<EOF;
a <- 2;
b <- 10;
c <- a * b;
print('ok');
print(c);
EOF
;

my $out2 = $R->run($cmds);

print ">>>\n$cmds\n";
print "<>\n$out2\n";



#$R->run(q `a <- 2`);
#$R->run(qq `print('a')`);
#$R->run(qq `print('R print')`);
#my $out = $R->run( q`print( 1 + 2 )` );
#$R->run( q`print( 1 + 2 )` );
#print "<>$out\n";

#$R->send("x<-c(1,2,3,4,5)");
#$R->send("y<-c(5,4,3,2,1)");
#$R->send('x11()');
##$R->send('jpeg("temp.jpg")');
#$R->send('pdf("temp.pdf")');
#$R->send("plot(x,y)");
#$R->send("dev.off()");

