#!/usr/bin/perl
#
# The input .tu file should be generated by:
#  tu -d joe -r start -z <tz> -x maez -c <solfile> -H -o <output_file> file.mtm
#
# To run:  perl tu2pm.pl <site> <start_date> <end_date>
#
use strict;
use lib "/home/grad/mfrsr/bin";
use Time::Local;
use Modules::Check_Site;
use Modules::Site_Info;
use Modules::Check_Dates;
use Modules::Determine_Dates;
use Modules::Time_Calculations;

# Make sure it is user mfrsr running the program
my $user = getlogin();
if ($user !~ /^mfrsr/) {
    print "\n Derp! You are running as user: $user\n";
    print " This program needs to be run by user \'mfrsr\' in order";
    print " to create\n the directories and files with proper ownership.\n";
    die "\n";
}

if (scalar@ARGV != 4) {usage();}
my $tli   = $ARGV[0];
my $type  = $ARGV[1];
my $start = $ARGV[2];
my $end   = $ARGV[3];
my $tli_type = join('_',$tli,$type);

&Check_Site ($tli_type);    # Make sure site is valid
&Check_Dates ($start,$end); # Make sure dates are valid
my @dates = &Determine_Dates ($start,$end);


# Gather site attributes from site_attributes file
#
my %info = &Site_Info ($tli_type); # Returns lat, lon, tz, type
my $lat  = $info{LAT};
my $lon  = $info{LON};
my $tz   = $info{TZ};
my $dir  = $info{DIR};
my $loc  = $info{LOC};

#print "HEY0: $lat : $lon : $tz : $dir\n";
#print "HEY1: $loc\n";
#sleep 100;

# Establish variable for temporary directory
my $tdir = "/tmp/mfrsrnightproc";
`rm -rf $tdir`;   # Delete temp dir and contents
`mkdir $tdir`;    # Create temp dir

# Copy raw files for date range requested into temp directory
#
my $path = "/data/Inst/MFR/${dir}/${tli}/${type}";  # Common path
foreach my $date (@dates) {
    my $yyyy = substr($date,0,4);
    `cp ${path}/tu/${yyyy}/${tli}_${type}_${date}_????_????_???.tu $tdir`;
}

chdir "$tdir";
my @files = `ls \*\.tu`;
if (scalar @files == 0) {die "\nNo .tu files to process";}

foreach my $file (@files) {
    chomp $file;
    print STDOUT "Processing: $file\n";
    my ($date,$hexb,$hexh,$sn) = (split /_/,$file)[2,3,4,5];
    $sn = (split '\.',$sn)[0];
    open (IF, "<$file");
    open (OF, ">${tli}_${type}_${date}_${hexb}_${hexh}_${sn}.pm");

    my ($srt,$dlv);

    my $next_flag = "Y";
    while (<IF>) {
	chomp;
	if ($next_flag eq "Y") {
	    my $idh = (split/\s+/, $_)[2];
	    $idh = sprintf "%04s",$idh;  # Pad with zeros, i.e. AA0 = 0AA0
	    if ($hexh =~ /\d\d\d\d/) {$hexh = int($hexh);} # Set to 0 if 0000
	    if ($hexh ne $idh) {
		print "\nID from filename:                $hexh\n";
                print "does not match string from file: $idh\n\n";
	    }
	    $next_flag = "N"; 
	    next;
	}
	my @el    = split/\s+/, $_;

###########################################
# This section does a first pass on the data with emperical limits
# for each channel.
#
#	if ($el[3]  < -150){next;}
#	if ($el[4]  < -40) {next;}
#	if ($el[5]  < -40) {next;}
#	if ($el[6]  < -45) {next;}
#	if ($el[7]  < -30) {next;}
#	if ($el[8]  < -20) {next;}
#	if ($el[12] < -15) {next;}
#	if ($el[12] > 15) {next;}

	my $size  = @el;

###########################################
# 19700101 - 19000101 = 2208988800 seconds
#
# Using the above constant to simplify time/date calculations.  That
# number is the elapsed seconds between 1 Jan 1900 and 1 Jan 1970.
#
	my $secs = int($el[0] * 86400 + 0.5)-86400-2208988800;
	my ($ss,$mn,$hh,$dd,$mm,$yyyy) = (gmtime($secs))[0,1,2,3,4,5];
	$yyyy += 1900;
	$mm++;

##########################################
# Uncomment five lines to use included SUNAE code rather than 
# values from tu.  (Note that tu also uses SUNAE).  Will then
# need to comment the following two lines.
#
	my $YYYYMMDDhhmmss = sprintf "%4d%2.2d%2.2d%2.2d%2.2d%2.2d",$yyyy,$mm,$dd,$hh,$mn,$ss;
        my @time_formats   = &Time_Calculations ($YYYYMMDDhhmmss);
        my $fYYYYMMDD = $time_formats[1];
        my $fdoy      = $time_formats[2];
        my $fyear     = $time_formats[3];

# Uncomment here for SUNAE
#	my $cdiy      = $time_formats[4];
#       my $fhr       = $time_formats[5];
#       my @sunae = sunae($yyyy,$cdiy,$fhr,$lat,$lon);
#       my $az    = $sunae[0];
#       my $sza   = 90-$sunae[1];
	my $az    = $el[$size-3];   # Comment if using preceding SUNAE calcs
	my $sza   = $el[$size-1];   # Comment if using preceding SUNAE calcs
#	print "@el\n";
#	print "\$az is: $az\n";
#	print "\$sza is: $sza\n";
#	sleep 1;

	my $csza  = cos(deg2rad($sza));

##########################################
# Head temperature calculation.  Code taken from Yankee MFRSR cal file.
#
	if ($el[1] > 2000) {
	    $srt = 6810 * (5000 / $el[1] -1);
	    $srt = 1.030852e-3+2.389179e-4 * 
		   log($srt) + 1.574641e-7 * log($srt)**3;
	    $srt = 1.0 / $srt - 273.12;
	} else {
	    $srt = -99.9;
	}
#	if ($srt < 30) {next;}	
##########################################
# Data logger supply voltage.  Code taken from Yankee MFRSR cal file.
#
	$dlv = $el[9] * 6.0 / 1000.0;
	
##########################################
# Begin print statement for outputting data files
#
	if ($sza > 108) {
	    printf OF "%14d %9.5f %12.7f %7.4f %3d %3d %3d %3d %3d %3d %3d\n",$YYYYMMDDhhmmss,$fdoy,$fyear,$srt,@el[2..8];
	}	    
    }
    close (OF);
    close (IF);
}

##########################################
# Check if .night file size is zero.  Delete if it is.
# Move non-zero .night files to regular directory structure
#
print "\n";
my @nightfiles = `ls \*\.pm`;
foreach my $night (@nightfiles) {
    chomp $night;
    if (-z $night) {
	print "$night is zero size and is being deleted\n";
	`rm -rf $night`;
    }
}
if (scalar @files == 0) {die "\nNo .tu files to process";}


##########################################
# Move .pm (night) files to appropriate directories
# Creates directories as necessary
#

print "\nMove .pm files to ${path}/pm/<YYYY>\n\n";
my @pmlist = `ls *.pm`;     # Need listing of files to extract year
foreach my $pmf (@pmlist) { # Foreach nighttime file
    chomp($pmf);
    my $yyyy = substr($pmf,10,4);

    if (! -e "${path}/pm/${yyyy}") {   # Exist?
	`mkdir -p ${path}/pm/${yyyy}`; # Create
    }
    `mv $pmf ${path}/pm/${yyyy}`;
}

##########################################
# Clean up
#
`rm -rf $tdir`;  # Purge temporary directory


# Subroutines below
#
# ===================================



sub usage {
    use strict;
    print "\n  To run, type \"perl tu2pm.pl <site> <type> <begin_date> <end_date>\"\n\n";
    print "  Site should be one of: bnd dra fpe gwn psu sxf tbl\n";
    print "  Dates should be in YYYYMMDD format\n\n";
    die;
}
1;

###############################################################################
# Subroutine sunae
#
# Calculates the Azimuth, Elevation, Solar Distance and Disk Diameter
#
# Fixed some errors in the refraction code on 20111108
#
###############################################################################
sub sunae () {
    use Math::Trig;
#    use strict;
    my $year = shift(@_);
    my $day  = shift(@_);
    my $hour = shift(@_); # Fractional hour
    my $lat  = shift(@_);
    my $long = shift(@_);

    my ($refrac);

    if ($year < 1950 || $year > 2050) {
        die "SUNAE--bad input variable YEAR ($year), stopped\n";
    }
    if ($day < 1 || $day > 366) {
        die "SUNAE--bad input variable DAY ($day), stopped\n";
    }
    if ($hour < -13.0 || $hour > 36.0) {
        die "SUNAE--bad input variable HOUR ($hour), stopped\n";
    }
    if ($lat < -90 || $lat > 90) {
        die "SUNAE--bad input variable LAT ($lat), stopped\n";
    }
    if ($long < -180 || $long > 180) {
        die "SUNAE--bad input variable LON ($long), stopped\n";
    }

    my $pi    = atan2(1,1) * 4;
    my $twopi = 2.0 * $pi;
    my $rpd   = $pi/180;

#                    ** current Julian date (actually add 2,400,000
#                    ** for true JD);  LEAP = leap days since 1949;
#                    ** 32916.5 is midnite 0 jan 1949 minus 2.4e6

    my $delta = $year - 1949;
    my $leap  = int($delta / 4);
    my $jd = 32916.5 + ($delta*365 + $leap + $day) + ($hour/24.);
#
#                    ** last yr of century not leap yr unless divisible
#                    ** by 400 (not executed for the allowed YEAR range,
#                    ** but left in so our successors can adapt this for
#                    ** the following 100 years)


    if (($year % 100 == 0) && ($year % 400 != 0)) {
        $jd = $jd - 1;
    }

#                     ** ecliptic coordinates
#                     ** 51545.0 + 2.4e6 = noon 1 jan 2000

    my $time = $jd - 51545.0;

#                    ** force mean longitude between 0 and 360 degs

    my $mnlong = 280.460 + (0.9856474 * $time);
#    $mnlong = ($mnlong % 360);
    while ($mnlong > 360) { $mnlong = $mnlong - 360; }

#                    ** mean anomaly in radians between 0 and 2*pi

    my $mnanom = 357.528 + (0.9856003 * $time);
#    $mnanom = ($mnanom % 360);
    if ($mnanom < 0) { $mnanom = $mnanom + 360; }
    $mnanom = $mnanom * $rpd;

#                    ** ecliptic longitude and obliquity
#                    ** of ecliptic in radians

    my $eclong = $mnlong + 1.915*sin($mnanom) + 0.020*sin(2*$mnanom);
    while ($eclong > 360) { $eclong = $eclong - 360; }

    my $oblqec = 23.439 - 0.0000004*$time;
    $eclong = $eclong*$rpd;
    $oblqec = $oblqec*$rpd;

#                    ** right ascension

    my $num  = cos($oblqec)*sin($eclong);
    my $den  = cos($eclong);
    my $temp = $num/$den;
    my $ra   = atan($num/$den);

#                    ** Force right ascension between 0 and 2*pi

    if ($den < 0) {
        $ra  = $ra + $pi;
    } elsif ($num < 0) {
        $ra  = $ra + $twopi;
    }

#                    ** declination

    my $dec = asin(sin($oblqec)*sin($eclong));

#                    ** Greenwich mean sidereal time in hours

    my $gmst = 6.697375 + 0.0657098242*$time + $hour;

#                    ** Hour not changed to sidereal time since
#                    ** 'time' includes the fractional day

    while ($gmst > 24) { $gmst = $gmst - 24; }

#                    ** local mean sidereal time in radians

    my $lmst  = $gmst + $long/15;
    while ($lmst > 24) { $lmst = $lmst - 24; }
    $lmst   = $lmst * 15 * $rpd;

#                    ** hour angle in radians between -pi and pi

    my $ha  = $lmst - $ra;
    if ($ha < -$pi) { $ha  = $ha + $twopi; }
    if ($ha > $pi) { $ha  = $ha - $twopi; }

#                    ** solar azimuth and elevation

    my $el = asin(sin($dec) * sin($lat * $rpd) +
               cos($dec) * cos($lat * $rpd) * cos($ha));

    my $az = asin(-cos($dec) * sin($ha) / cos($el));

#                    ** Put azimuth between 0 and 2*pi radians

    if ((sin($dec) - sin($el) * sin($lat * $rpd)) > 0) {
        if (sin($az) < 0) { $az = $az + $twopi; }
    } else {
        $az = $pi - $az;

    }

#                     ** Convert elevation and azimuth to degrees
    $az  =  $az / $rpd;
    $el  =  $el / $rpd;

#  ======== Refraction correction for U.S. Standard Atmos. ==========
#      (assumes elevation in degs) (3.51823=1013.25 mb/288 K)

    if ($el > 19.225 ) {
        $refrac = 0.00452*3.51823 / tan($el*$rpd);
    } elsif ($el > -0.766 && $el < 19.225 ) {
        $refrac = 3.51823 * (0.1594 + 0.0196*$el + 0.00002*$el**2) /
            (1 + 0.505*$el + 0.0845*$el**2);

    } elsif ($el <= -0.766 ) {
        $refrac = 0.0;
    }
    $el = $el + $refrac;

# ===================================================================

#                   ** distance to sun in A.U. & diameter in degs

    my $soldst = 1.00014 - 0.01671*cos($mnanom) - 0.00014*cos(2*$mnanom);
    my $soldia = 0.5332 / $soldst;

    if ($el < -90 || $el > 90) {
        die "SUNAE--Output argument EL ($el) out of range\n";
    }
    if ($az < 0 || $az > 360) {
        die "SUNAE--Output argument AZ out of range\n";
    }
    my @returnary = ($az, $el, $soldst, $soldia);
    return (@returnary);
}
1;
