#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  3 13:29:47 2023

@author: hagen
"""
import productomator.lab as prolab
import SurfRadPy.realtime_aod as sufrtaod

if __name__ == '__main__':
    autothis = sufrtaod.mfrsr_AOD_lev0()    
    autothis.process_all()
    
    auto = prolab.Automation(autothis)    
    auto.log()