#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  6 09:44:01 2023

@author: hagen
"""

import productomator.lab as prolab
import SurfRadPy.aodinversion as sfraodinv

if __name__ == '__main__':
    reporter = prolab.Reporter('aodinversion',
                             log_folder='/home/grad/htelg/.processlogs/',
                             reporting_frequency=(6, 'h'),
                            )
    run = sfraodinv.AODInversion(reporter = reporter)
    print(f'workplan.shape: {run.workplan.shape}')
    run.run_product()
    